/* eslint-disable vue/one-component-per-file -- Focused editor stubs. */
import { mount, flushPromises } from '@vue/test-utils'
import { computed, defineComponent, h, inject, provide, type Ref } from 'vue'
import { createPinia } from 'pinia'
import { createI18n } from 'vue-i18n'
import { beforeEach, expect, it, vi } from 'vitest'
import { useAuthStore } from '@/stores/auth'
import Dialog from '@/components/finance/BankReconciliationDialog.vue'
import en from '@/i18n/locales/en-US'
import * as api from '@/api/finance-v2'
vi.mock('@/api/finance-v2', () => ({ listFinancePayments: vi.fn(), listBankStatementLines: vi.fn(), listFinanceBankAccounts: vi.fn(), listBankReconciliations: vi.fn(), reconcileBankStatement: vi.fn(), reverseBankReconciliation: vi.fn() }))
const slot = defineComponent({ template: '<div><slot /></div>' })
const button = defineComponent({ props: { disabled: Boolean, loading: Boolean }, template: '<button :disabled="disabled || loading"><slot /></button>' })
const dialog = defineComponent({ props: { modelValue: Boolean }, template: '<section v-if="modelValue"><slot /><slot name="footer" /></section>' })
const select = defineComponent({ props: { modelValue: { type: String, default: '' } }, emits: ['update:modelValue','change'], template: `<select :value="modelValue" @change="$emit('update:modelValue', $event.target.value); $emit('change')"><option value=""></option><slot /></select>` })
const option = defineComponent({ props: { value: { type: String, default: '' }, label: { type: String, default: '' } }, template: '<option :value="value">{{ label }}</option>' })
const text = defineComponent({ props: { modelValue: { type: String, default: '' } }, emits: ['update:modelValue'], template: `<textarea :value="modelValue" @input="$emit('update:modelValue', $event.target.value)" />` })
const alert = defineComponent({ props: { title: { type: String, default: '' } }, template: '<p role="alert">{{ title }}</p>' })
const table = defineComponent({ props: { data: { type: Array, default: () => [] } }, setup(props,{slots}) { provide('rows',computed(()=>props.data));return ()=>h('div',slots.default?.()) } })
const column = defineComponent({ setup(_,{slots}) { const rows=inject<Ref<api.BankReconciliation[]>>('rows')!;return ()=>h('div',rows.value.flatMap(row=>slots.default?.({row})??[])) } })
const payment = (patch:Partial<api.FinancePayment>={}):api.FinancePayment=>({id:'p',number:'RC-1',paymentType:'RECEIPT',partyType:'CUSTOMER',partyId:'customer',bankAccountId:'b',status:'POSTED',allocationStatus:'UNALLOCATED',accountingDate:'2026-10-05',currencyCode:'CNY',amount:30,allocatedAmount:0,version:1,allocations:[],...patch})
const statement = (patch:Partial<api.BankStatementLine>={}):api.BankStatementLine=>({id:'s',bankAccountId:'b',transactionDate:'2025-01-01',amount:10,currencyCode:'CNY',externalReference:'REF-10',reconciliationStatus:'UNMATCHED',...patch})
const record = (patch:Partial<api.BankReconciliation>={}):api.BankReconciliation=>({id:'r',number:'BR-1',bankAccountId:'b',status:'CONFIRMED',totalStatementAmount:10,totalPaymentAmount:10,differenceAmount:0,links:[{statementLineId:'s',paymentId:'p',matchedAmount:10}],...patch})
function render(permissions=['finance:view','finance:bank'],scope:'ALL'|'SELF'='ALL') {const pinia=createPinia();useAuthStore(pinia).user={id:'u',username:'u',displayName:'u',organizationId:'o',organizationName:'o',departmentId:null,dataScope:scope,permissions,roles:[],mustChangePassword:false};return mount(Dialog,{props:{modelValue:true},global:{plugins:[pinia,createI18n({legacy:false,locale:'en-US',messages:{'en-US':en}})],stubs:{ElDialog:dialog,ElButton:button,ElAlert:alert,ElForm:slot,ElFormItem:slot,ElSelect:select,ElOption:option,ElInput:text,ElTable:table,ElTableColumn:column}}})}
type Wrapper=ReturnType<typeof render>
async function click(w:Wrapper,label:string){await w.findAll('button').find(b=>b.text()===label)!.trigger('click');await flushPromises()}
async function choose(w:Wrapper,s='s',p='p'){await w.findAll('select')[0]!.setValue(s);await w.findAll('select')[1]!.setValue(p)}
beforeEach(()=>{vi.resetAllMocks();vi.mocked(api.listFinancePayments).mockResolvedValue([payment()]);vi.mocked(api.listBankStatementLines).mockResolvedValue([statement()]);vi.mocked(api.listFinanceBankAccounts).mockResolvedValue([{id:'b',code:'BANK',name:'Bank',currencyCode:'CNY'}]);vi.mocked(api.listBankReconciliations).mockResolvedValue([]);vi.mocked(api.reconcileBankStatement).mockResolvedValue(record());vi.mocked(api.reverseBankReconciliation).mockResolvedValue(record({status:'REVERSED'}))})
it('filters bank, currency, direction, state and remaining balance while including all dates',async()=>{vi.mocked(api.listBankStatementLines).mockResolvedValue([statement(),statement({id:'matched',reconciliationStatus:'MATCHED',externalReference:'Matched'}),statement({id:'zero',amount:0,externalReference:'Zero'}),statement({id:'foreign',bankAccountId:'other',externalReference:'Other bank'})]);vi.mocked(api.listFinancePayments).mockResolvedValue([payment(),payment({id:'small',number:'Too small',amount:5}),payment({id:'wrong-bank',number:'Wrong bank',bankAccountId:'other'}),payment({id:'fx',number:'Wrong currency',currencyCode:'USD'}),payment({id:'out',number:'Wrong direction',paymentType:'PAYMENT'}),payment({id:'draft',number:'Draft',status:'DRAFT'})]);vi.mocked(api.listBankReconciliations).mockResolvedValue([record(),record({id:'old',status:'REVERSED',links:[{statementLineId:'old',paymentId:'p',matchedAmount:20}]})]);const w=render();await flushPromises();expect(w.findAll('select')[0]!.findAll('option')).toHaveLength(2);await w.findAll('select')[0]!.setValue('s');const options=w.findAll('select')[1]!.text();expect(options).toContain('RC-1 · 20.00 CNY');expect(options).not.toContain('Wrong');expect(options).not.toContain('Too small');expect(options).not.toContain('Draft');await w.findAll('select')[1]!.setValue('p');await click(w,'Confirm match');expect(api.reconcileBankStatement).toHaveBeenCalledWith('b','s','p',10,expect.any(String))})
it('matches negative statements to payments and customer refunds',async()=>{vi.mocked(api.listBankStatementLines).mockResolvedValue([statement({amount:-12})]);vi.mocked(api.listFinancePayments).mockResolvedValue([payment(),payment({id:'out',number:'PY-1',paymentType:'PAYMENT'}),payment({id:'refund',number:'CR-1',paymentType:'CUSTOMER_REFUND'})]);const w=render();await flushPromises();await choose(w,'s','out');expect(w.findAll('select')[1]!.text()).not.toContain('RC-1');expect(w.findAll('select')[1]!.text()).toContain('CR-1');await click(w,'Confirm match');expect(api.reconcileBankStatement).toHaveBeenCalledWith('b','s','out',12,expect.any(String))})
it('splits a receipt across two full statement lines and uses a new key for the next selection',async()=>{const lines=[statement(),statement({id:'s2',externalReference:'REF-20',amount:20})];const history:api.BankReconciliation[]=[];vi.mocked(api.listBankStatementLines).mockImplementation(async()=>lines.map(x=>({...x})));vi.mocked(api.listBankReconciliations).mockImplementation(async()=>[...history]);vi.mocked(api.reconcileBankStatement).mockImplementation(async(_b,s,p,amount)=>{lines.find(x=>x.id===s)!.reconciliationStatus='MATCHED';const result=record({id:s,links:[{statementLineId:s,paymentId:p,matchedAmount:amount}]});history.push(result);return result});const w=render();await flushPromises();await choose(w);await click(w,'Confirm match');await choose(w,'s2');expect(w.text()).toContain('20.00 CNY');await click(w,'Confirm match');expect(w.text()).toContain('No eligible unmatched');const calls=vi.mocked(api.reconcileBankStatement).mock.calls;expect(calls).toHaveLength(2);expect(calls[0]![4]).not.toBe(calls[1]![4]);expect(w.emitted('changed')).toHaveLength(2)})
it('keeps an unchanged request key for explicit retry and prevents pending duplicate writes',async()=>{let reject!:(e:Error)=>void;vi.mocked(api.reconcileBankStatement).mockImplementationOnce(()=>new Promise((_r,j)=>{reject=j}));const w=render();await flushPromises();await choose(w);await click(w,'Confirm match');await click(w,'Confirm match');await click(w,'Close');expect(w.emitted('update:modelValue')).toBeUndefined();expect(api.reconcileBankStatement).toHaveBeenCalledTimes(1);reject(new Error('offline'));await flushPromises();expect(w.text()).toContain('Check refreshed records');await click(w,'Confirm match');expect(vi.mocked(api.reconcileBankStatement).mock.calls[0]).toEqual(vi.mocked(api.reconcileBankStatement).mock.calls[1])})
it('refreshes after a lost response without replaying a committed match',async()=>{vi.mocked(api.reconcileBankStatement).mockImplementation(async()=>{vi.mocked(api.listBankStatementLines).mockResolvedValue([statement({reconciliationStatus:'MATCHED'})]);vi.mocked(api.listBankReconciliations).mockResolvedValue([record()]);throw new Error('lost response')});const w=render();await flushPromises();await choose(w);await click(w,'Confirm match');expect(api.reconcileBankStatement).toHaveBeenCalledTimes(1);expect(w.text()).toContain('Confirmed');expect(w.text()).toContain('REF-10 → RC-1');expect(w.findAll('select')[0]!.findAll('option')).toHaveLength(1);expect(w.emitted('changed')).toHaveLength(1)})
it('requires reversal reason and restores candidates while keeping reversed history',async()=>{vi.mocked(api.listBankStatementLines).mockResolvedValue([statement({reconciliationStatus:'MATCHED'})]);vi.mocked(api.listBankReconciliations).mockResolvedValue([record()]);vi.mocked(api.reverseBankReconciliation).mockImplementation(async()=>{vi.mocked(api.listBankStatementLines).mockResolvedValue([statement()]);vi.mocked(api.listBankReconciliations).mockResolvedValue([record({status:'REVERSED'})]);return record({status:'REVERSED'})});const w=render();await flushPromises();await click(w,'Reverse reconciliation');expect(w.text()).toContain('BR-1');await w.find('textarea').setValue(' ');await click(w,'Confirm reversal');expect(api.reverseBankReconciliation).not.toHaveBeenCalled();await w.find('textarea').setValue('  Correct match  ');await click(w,'Confirm reversal');expect(api.reverseBankReconciliation).toHaveBeenCalledWith('r','Correct match');expect(w.text()).toContain('Reversed');await choose(w);expect(w.text()).toContain('30.00 CNY');expect(w.findAll('button').some(b=>b.text()==='Reverse reconciliation')).toBe(false)})
it('does not retry reversal when the response is lost but refreshed status is reversed',async()=>{vi.mocked(api.listBankReconciliations).mockResolvedValue([record()]);vi.mocked(api.reverseBankReconciliation).mockImplementation(async()=>{vi.mocked(api.listBankReconciliations).mockResolvedValue([record({status:'REVERSED'})]);throw new Error('lost response')});const w=render();await flushPromises();await click(w,'Reverse reconciliation');await w.find('textarea').setValue('Correction');await click(w,'Confirm reversal');expect(api.reverseBankReconciliation).toHaveBeenCalledTimes(1);expect(w.text()).toContain('Reversed');expect(w.find('textarea').exists()).toBe(false)})
it('requires view, bank permission and ALL scope',async()=>{for(const [permissions,scope] of [[['finance:view'],'ALL'],[['finance:bank'],'ALL'],[['finance:view','finance:bank'],'SELF']] as const){const w=render([...permissions],scope);await flushPromises();expect(api.listBankReconciliations).not.toHaveBeenCalled();expect(api.listFinancePayments).not.toHaveBeenCalled();expect(w.find('select').exists()).toBe(false);w.unmount()}})
it('blocks actions on load failure and permits explicit reload',async()=>{vi.mocked(api.listBankReconciliations).mockRejectedValueOnce(new Error('offline'));const w=render();await flushPromises();expect(w.text()).toContain('Unable to load current reconciliation');expect(w.find('select').exists()).toBe(false);await click(w,'Reload');await choose(w);await click(w,'Confirm match');expect(api.reconcileBankStatement).toHaveBeenCalledTimes(1)})
it('ignores late reads after dialog close',async()=>{let resolve!:(v:api.BankReconciliation[])=>void;vi.mocked(api.listBankReconciliations).mockImplementationOnce(()=>new Promise(r=>{resolve=r}));const w=render();await w.setProps({modelValue:false});resolve([record()]);await flushPromises();expect(w.text()).not.toContain('BR-1');expect(api.reconcileBankStatement).not.toHaveBeenCalled()})
it('fails closed when the server cannot provide reconciliation links',async()=>{vi.mocked(api.listBankReconciliations).mockResolvedValue([{...record(),links:undefined}] as unknown as api.BankReconciliation[]);const w=render();await flushPromises();expect(w.text()).toContain('Unable to load current reconciliation');expect(w.find('select').exists()).toBe(false)})
