/* eslint-disable vue/one-component-per-file -- Focused editor stubs. */
import { mount, flushPromises } from '@vue/test-utils'
import { defineComponent } from 'vue'
import { createPinia } from 'pinia'
import { createI18n } from 'vue-i18n'
import { beforeEach, expect, it, vi } from 'vitest'
import { useAuthStore } from '@/stores/auth'
import Dialog from '@/components/finance/CreditNoteDialog.vue'
import en from '@/i18n/locales/en-US'
import * as api from '@/api/finance-v2'
vi.mock('@/api/finance-v2', () => ({ listFinanceInvoices: vi.fn(), getFinanceInvoice: vi.fn(), createFinanceInvoice: vi.fn() }))
import * as master from '@/api/master-data'
vi.mock('@/api/master-data', () => ({ getOrganizationSettings: vi.fn() }))
const slot = defineComponent({ template: '<div><slot /></div>' })
const button = defineComponent({ props: { disabled: Boolean, loading: Boolean }, template: '<button :disabled="disabled || loading"><slot /></button>' })
const dialog = defineComponent({ props: { modelValue: Boolean }, template: '<section v-if="modelValue"><slot /><slot name="footer" /></section>' })
const select = defineComponent({ props: { modelValue: { type: String, default: '' } }, emits: ['update:modelValue','change'], template: `<select :value="modelValue" @change="$emit('update:modelValue', $event.target.value); $emit('change')"><option value=""></option><slot /></select>` })
const option = defineComponent({ props: { value: { type: String, default: '' }, label: { type: String, default: '' } }, template: '<option :value="value">{{ label }}</option>' })
const alert = defineComponent({ props: { title: { type: String, default: '' } }, template: '<p role="alert">{{ title }}</p>' })
const number = defineComponent({ props: { modelValue: { type: Number, default: 1 } }, emits: ['update:modelValue'], template: `<input type="number" :value="modelValue" @input="$emit('update:modelValue', Number($event.target.value))" />` })
const row=(patch:Partial<api.FinanceInvoiceDetail>={}):api.FinanceInvoiceDetail=>({id:'original',number:'PI-1',documentType:'SUPPLIER_INVOICE',partyType:'SUPPLIER',partyId:'supplier',status:'POSTED',settlementStatus:'UNPAID',currencyCode:'CNY',totalAmount:23.76,allocatedAmount:0,creditedAmount:0,exchangeRate:1,accountingDate:'2026-10-07',dueDate:'2026-11-07',matchStatus:'MATCHED',version:1,lines:[{id:'real-line',lineNo:1,itemId:'item',description:'Original item',quantity:2,unitPrice:12,discountRate:10,taxRate:10,creditedQuantity:0,reversalAccountCode:'2005',projectId:'project',matchQuantityVariance:0,matchPriceVarianceRate:0,matchTaxVariance:0,sources:[]}],...patch})
function render(permissions=['finance:view','finance:invoice'],scope:'ALL'|'SELF'='ALL') {const pinia=createPinia();useAuthStore(pinia).user={id:'u',username:'u',displayName:'u',organizationId:'o',organizationName:'o',departmentId:null,dataScope:scope,permissions,roles:[],mustChangePassword:false};return mount(Dialog,{props:{modelValue:true},global:{plugins:[pinia,createI18n({legacy:false,locale:'en-US',messages:{'en-US':en}})],stubs:{ElDialog:dialog,ElButton:button,ElAlert:alert,ElForm:slot,ElFormItem:slot,ElSelect:select,ElOption:option,ElInputNumber:number}}})}
type Wrapper=ReturnType<typeof render>
async function click(w:Wrapper,label:string) {await w.findAll('button').find(b=>b.text()===label)!.trigger('click');await flushPromises()}
async function choose(w:Wrapper,q='1') {await w.findAll('select')[0]!.setValue('original');await flushPromises();await w.findAll('select')[1]!.setValue('real-line');await w.find('input[type=number]').setValue(q)}
beforeEach(()=>{vi.clearAllMocks();vi.mocked(api.listFinanceInvoices).mockReset().mockResolvedValue([row()]);vi.mocked(api.getFinanceInvoice).mockReset().mockResolvedValue(row());vi.mocked(api.createFinanceInvoice).mockReset().mockResolvedValue({} as api.FinanceInvoice);vi.mocked(master.getOrganizationSettings).mockReset().mockResolvedValue({baseCurrencyCode:'CNY'} as Awaited<ReturnType<typeof master.getOrganizationSettings>>)})
it('retains original terms, posted accrual account, real source ids and saves supplier credit as a draft',async()=>{const w=render();await flushPromises();await choose(w);expect(w.text()).toContain('11.88');await click(w,'Save');expect(api.createFinanceInvoice).toHaveBeenCalledWith(expect.objectContaining({documentType:'SUPPLIER_CREDIT',originalInvoiceId:'original',partyId:'supplier',currencyCode:'CNY',exchangeRate:1,lines:[expect.objectContaining({itemId:'item',projectId:'project',quantity:1,unitPrice:12,discountRate:10,taxRate:10,accountCode:'2005',sources:[{sourceType:'ORIGINAL_INVOICE_LINE',sourceId:'original',sourceLineId:'real-line',quantity:1,amount:10.8}]})]}),expect.any(String));expect(w.emitted('update:modelValue')).toEqual([[false]]);expect(w.emitted('changed')).toHaveLength(1)})
it('supports customer credit and blocks amounts exceeding unallocated balance',async()=>{vi.mocked(api.getFinanceInvoice).mockResolvedValue(row({documentType:'SALES_INVOICE',partyType:'CUSTOMER',partyId:'customer',allocatedAmount:15}));const w=render();await flushPromises();await choose(w);await click(w,'Save');expect(api.createFinanceInvoice).not.toHaveBeenCalled();await w.find('input').setValue('0.5');await click(w,'Save');expect(api.createFinanceInvoice).toHaveBeenCalledWith(expect.objectContaining({documentType:'CUSTOMER_CREDIT',partyId:'customer'}),expect.any(String))})
it('excludes foreign currency, drafts, credits and exhausted invoices',async()=>{vi.mocked(api.listFinanceInvoices).mockResolvedValue([row(),row({id:'fx',currencyCode:'USD'}),row({id:'draft',status:'DRAFT'}),row({id:'credit',documentType:'SUPPLIER_CREDIT'}),row({id:'paid',allocatedAmount:23.76})]);const w=render();await flushPromises();expect(w.findAll('option')).toHaveLength(2)})
it('blocks exhausted quantities or missing actual posted account',async()=>{vi.mocked(api.getFinanceInvoice).mockResolvedValue(row({lines:[{...row().lines[0]!,creditedQuantity:2},{...row().lines[0]!,id:'missing',reversalAccountCode:undefined}]}));const w=render();await flushPromises();await w.find('select').setValue('original');await flushPromises();expect(w.findAll('select')[1]!.findAll('option')).toHaveLength(1);await click(w,'Save');expect(api.createFinanceInvoice).not.toHaveBeenCalled()})
it('reuses the key on explicit unchanged retry and prevents duplicate submits and closing',async()=>{let reject!:(e:Error)=>void;vi.mocked(api.createFinanceInvoice).mockImplementationOnce(()=>new Promise((_r,j)=>{reject=j}));const w=render();await flushPromises();await choose(w);await click(w,'Save');await click(w,'Save');await click(w,'Close');expect(api.createFinanceInvoice).toHaveBeenCalledTimes(1);expect(w.emitted('update:modelValue')).toBeUndefined();reject(new Error('lost'));await flushPromises();await w.findAll('select')[1]!.setValue('real-line');await click(w,'Save');expect(vi.mocked(api.createFinanceInvoice).mock.calls[0]![1]).toBe(vi.mocked(api.createFinanceInvoice).mock.calls[1]![1])})
it('changes the key when the quantity changes after failed save',async()=>{vi.mocked(api.createFinanceInvoice).mockRejectedValueOnce(new Error('lost'));const w=render();await flushPromises();await choose(w);await click(w,'Save');await w.findAll('select')[1]!.setValue('real-line');await w.find('input').setValue('0.5');await click(w,'Save');expect(vi.mocked(api.createFinanceInvoice).mock.calls[0]![1]).not.toBe(vi.mocked(api.createFinanceInvoice).mock.calls[1]![1])})
it('fails closed on detail read failure and drops late details after closing',async()=>{vi.mocked(api.getFinanceInvoice).mockRejectedValueOnce(new Error('offline'));const w=render();await flushPromises();await w.find('select').setValue('original');await flushPromises();await click(w,'Save');expect(api.createFinanceInvoice).not.toHaveBeenCalled();let resolve!:(v:api.FinanceInvoiceDetail)=>void;vi.mocked(api.getFinanceInvoice).mockImplementationOnce(()=>new Promise(r=>{resolve=r}));await click(w,'Reload');await w.setProps({modelValue:false});resolve(row());await flushPromises();expect(w.find('select').exists()).toBe(false)})
it('requires view, invoice and ALL scope without unauthorized reads',async()=>{for(const [p,s] of [[['finance:view'],'ALL'],[['finance:invoice'],'ALL'],[['finance:view','finance:invoice'],'SELF']] as const){const w=render([...p],s);await flushPromises();expect(api.listFinanceInvoices).not.toHaveBeenCalled();expect(master.getOrganizationSettings).not.toHaveBeenCalled();w.unmount()}})
