/* eslint-disable vue/one-component-per-file -- Focused financial action stubs. */
import { mount, flushPromises } from '@vue/test-utils'
import { defineComponent } from 'vue'
import { createPinia } from 'pinia'
import { createI18n } from 'vue-i18n'
import { beforeEach, expect, it, vi } from 'vitest'
import { useAuthStore } from '@/stores/auth'
import Dialog from '@/components/finance/CurrencyRevaluationDialog.vue'
import en from '@/i18n/locales/en-US'
import * as api from '@/api/finance-v2'
import * as master from '@/api/master-data'
vi.mock('@/api/finance-v2',()=>({listCurrencyRevaluations:vi.fn(),createCurrencyRevaluation:vi.fn(),reverseCurrencyRevaluation:vi.fn()}))
vi.mock('@/api/master-data',()=>({getOrganizationSettings:vi.fn(),listMasterData:vi.fn()}))
const slot=defineComponent({template:'<div><slot /></div>'})
const button=defineComponent({props:{disabled:Boolean,loading:Boolean},template:'<button :disabled="disabled || loading"><slot /></button>'})
const dialog=defineComponent({props:{modelValue:Boolean},template:'<section v-if="modelValue"><slot /><slot name="footer" /></section>'})
const alert=defineComponent({props:{title:{type:String,default:''}},template:'<p>{{title}}</p>'})
const select=defineComponent({props:{modelValue:{type:String,default:''}},emits:['update:modelValue'],template:`<select :value="modelValue" @change="$emit('update:modelValue',$event.target.value)"><option value=""></option><slot /></select>`})
const option=defineComponent({props:{value:{type:String,default:''},label:{type:String,default:''}},template:'<option :value="value">{{label}}</option>'})
const number=defineComponent({props:{modelValue:{type:Number,default:0}},emits:['update:modelValue'],template:`<input type="number" :value="modelValue" @input="$emit('update:modelValue',Number($event.target.value))" />`})
const text=defineComponent({props:{modelValue:{type:String,default:''}},emits:['update:modelValue'],template:`<input type="text" :value="modelValue" @input="$emit('update:modelValue',$event.target.value)" />`})
const date=defineComponent({props:{modelValue:{type:String,default:''}},emits:['update:modelValue'],template:`<input type="date" :value="modelValue" @input="$emit('update:modelValue',$event.target.value)" />`})
const checkbox=defineComponent({props:{modelValue:Boolean},emits:['update:modelValue'],template:`<label><input type="checkbox" :checked="modelValue" @change="$emit('update:modelValue',$event.target.checked)" /><slot /></label>`})
const posted=(patch:Partial<api.CurrencyRevaluation>={}):api.CurrencyRevaluation=>({id:'real-valuation',number:'RV-1',accountingDate:'2026-10-01',currencyCode:'USD',rate:7.4,totalGain:10,totalLoss:0,journalEntryId:'real-journal',status:'POSTED',...patch})
function render(permissions=['finance:view','finance:budget','finance:post','master:view'],scope:'ALL'|'SELF'='ALL') {const pinia=createPinia();useAuthStore(pinia).user={id:'u',username:'u',displayName:'u',organizationId:'o',organizationName:'o',departmentId:null,dataScope:scope,permissions,roles:[],mustChangePassword:false};return mount(Dialog,{props:{modelValue:true},global:{plugins:[pinia,createI18n({legacy:false,locale:'en-US',messages:{'en-US':en}})],stubs:{ElDialog:dialog,ElAlert:alert,ElButton:button,ElForm:slot,ElFormItem:slot,ElSelect:select,ElOption:option,ElInputNumber:number,ElInput:text,ElDatePicker:date,ElCheckbox:checkbox}}})}
type W=ReturnType<typeof render>
const click=async(w:W,label:string)=>{await w.findAll('button').find(b=>b.text()===label)!.trigger('click');await flushPromises()}
async function fill(w:W,n='7.4'){await w.find('select').setValue('USD');await w.find('input[type=number]').setValue(n);await w.find('input[type=checkbox]').setValue(true)}
beforeEach(()=>{vi.clearAllMocks();vi.mocked(api.listCurrencyRevaluations).mockReset().mockResolvedValue([]);vi.mocked(api.createCurrencyRevaluation).mockReset().mockResolvedValue(posted());vi.mocked(api.reverseCurrencyRevaluation).mockReset().mockResolvedValue({});vi.mocked(master.getOrganizationSettings).mockReset().mockResolvedValue({baseCurrencyCode:'CNY'} as master.OrganizationSettings);vi.mocked(master.listMasterData).mockReset().mockResolvedValue({content:[{id:'usd',code:'USD',active:true},{id:'base',code:'CNY',active:true},{id:'off',code:'EUR',active:false}],totalPages:1} as Awaited<ReturnType<typeof master.listMasterData>> )})
it('posts only an explicitly confirmed foreign accounting rate with an idempotency key',async()=>{const w=render();await flushPromises();expect(w.findAll('option').map(o=>o.text())).toContain('USD');expect(w.findAll('option').map(o=>o.text())).not.toContain('CNY');await fill(w);await click(w,'Confirm posting');expect(api.createCurrencyRevaluation).toHaveBeenCalledWith({currencyCode:'USD',rate:7.4,accountingDate:expect.stringMatching(/^\d{4}-\d{2}-\d{2}$/)},expect.any(String));expect(w.emitted('changed')).toHaveLength(1)})
it('requires confirmation again after changing the rate and rejects nonpositive or overprecision rates',async()=>{const w=render();await flushPromises();for(const n of ['0','-1','7.123456789']){await fill(w,n);await click(w,'Confirm posting')}expect(api.createCurrencyRevaluation).not.toHaveBeenCalled();await fill(w);await w.find('input[type=number]').setValue('7.5');await click(w,'Confirm posting');expect(api.createCurrencyRevaluation).not.toHaveBeenCalled()})
it('reads history without master reads for view-only users and excludes inactive journals from reversal',async()=>{vi.mocked(api.listCurrencyRevaluations).mockResolvedValue([posted(),posted({id:'reversed',status:'REVERSED'}),posted({id:'zero',status:'NO_ADJUSTMENT',journalEntryId:undefined})]);const w=render(['finance:view','finance:post']);await flushPromises();expect(master.getOrganizationSettings).not.toHaveBeenCalled();expect(master.listMasterData).not.toHaveBeenCalled();expect(w.text()).toContain('No adjustment');expect(w.findAll('option')).toHaveLength(2);await w.find('select').setValue('real-valuation');await w.find('input[type=text]').setValue('Correct confirmed period rate');await w.find('input[type=checkbox]').setValue(true);await click(w,'Reverse selected journal');expect(api.reverseCurrencyRevaluation).toHaveBeenCalledWith('real-valuation',expect.any(String),'Correct confirmed period rate',expect.any(String))})
it('blocks a second active valuation and rejects missing reversal reasons or invalid dates',async()=>{vi.mocked(api.listCurrencyRevaluations).mockResolvedValue([posted()]);const w=render();await flushPromises();await fill(w);await click(w,'Confirm posting');expect(api.createCurrencyRevaluation).not.toHaveBeenCalled();await w.findAll('select')[1]!.setValue('real-valuation');await w.findAll('input[type=checkbox]')[1]!.setValue(true);await click(w,'Reverse selected journal');expect(api.reverseCurrencyRevaluation).not.toHaveBeenCalled();await w.find('input[type=text]').setValue('Correction');await w.find('input[type=date]').setValue('2026-09-30');await w.findAll('input[type=checkbox]')[1]!.setValue(true);await click(w,'Reverse selected journal');expect(api.reverseCurrencyRevaluation).not.toHaveBeenCalled()})
it('retains the same request key on explicit uncertain retry, blocks double submit and close',async()=>{let reject!:(e:Error)=>void;vi.mocked(api.createCurrencyRevaluation).mockImplementationOnce(()=>new Promise((_r,j)=>{reject=j}));const w=render();await flushPromises();await fill(w);await click(w,'Confirm posting');await click(w,'Confirm posting');await click(w,'Close');expect(api.createCurrencyRevaluation).toHaveBeenCalledTimes(1);expect(w.emitted('update:modelValue')).toBeUndefined();reject(new Error('lost'));await flushPromises();await click(w,'Confirm posting');expect(vi.mocked(api.createCurrencyRevaluation).mock.calls[0]![1]).toBe(vi.mocked(api.createCurrencyRevaluation).mock.calls[1]![1])})
it('fails closed on reads and ignores late history after close',async()=>{vi.mocked(api.listCurrencyRevaluations).mockRejectedValueOnce(new Error('offline'));const w=render();await flushPromises();expect(w.text()).toContain('Unable to load');let resolve!:(r:api.CurrencyRevaluation[])=>void;vi.mocked(api.listCurrencyRevaluations).mockImplementationOnce(()=>new Promise(r=>{resolve=r}));await click(w,'Reload');await w.setProps({modelValue:false});resolve([posted()]);await flushPromises();expect(w.find('table').exists()).toBe(false)})
it('requires finance view and ALL scope before any reads',async()=>{for(const [p,s] of [[['finance:budget','master:view'],'ALL'],[['finance:view','finance:budget','master:view'],'SELF']] as const){const w=render([...p],s);await flushPromises();expect(api.listCurrencyRevaluations).not.toHaveBeenCalled();expect(master.listMasterData).not.toHaveBeenCalled();w.unmount()}})
