/* eslint-disable vue/one-component-per-file -- UI stubs for focused form behavior. */
import { mount, flushPromises } from '@vue/test-utils'
import { computed, defineComponent, h, inject, provide, type Ref } from 'vue'
import { createPinia } from 'pinia'
import { createI18n } from 'vue-i18n'
import { beforeEach, expect, it, vi } from 'vitest'
import { useAuthStore } from '@/stores/auth'
import Panel from '@/components/finance/FinanceClosurePanel.vue'
import en from '@/i18n/locales/en-US'
import * as api from '@/api/finance-v2'
import * as master from '@/api/master-data'
vi.mock('@/api/finance-v2', () => ({ getFinanceDashboard: vi.fn(), listFinanceInvoices: vi.fn(), listFinancePayments: vi.fn(), listBankStatementLines: vi.fn(), createFinanceInvoice: vi.fn(), createFinancePayment: vi.fn(), postFinanceInvoice: vi.fn(), postFinancePayment: vi.fn(), allocateFinancePayment: vi.fn(), reverseFinanceAllocation: vi.fn() }))
vi.mock('@/api/master-data', () => ({ listMasterData: vi.fn(), getOrganizationSettings: vi.fn() }))
const table = defineComponent({ props: { data: { type: Array, default: () => [] } }, setup(props, { slots }) { provide('rows', computed(() => props.data)); return () => h('div', slots.default?.()) } })
const column = defineComponent({ setup(_, { slots }) { const rows = inject<Ref<api.FinanceInvoice[]>>('rows')!; return () => h('div', rows.value.flatMap(row => slots.default?.({ row }) ?? [])) } })
const slot = defineComponent({ template: '<div><slot /></div>' })
const dialog = defineComponent({ props: { modelValue: Boolean }, template: '<section v-if="modelValue" class="editor"><slot /><slot name="footer" /></section>' })
const button = defineComponent({ props: { disabled: Boolean, loading: Boolean }, template: '<button :disabled="disabled || loading"><slot /></button>' })
const select = defineComponent({ props: { modelValue: { type: [String, Number], default: '' }, disabled: Boolean }, emits: ['update:modelValue','change'], template: `<select :value="modelValue" :disabled="disabled" @change="$emit('update:modelValue', $event.target.value); $emit('change', $event.target.value)"><option value=""></option><slot /></select>` })
const option = defineComponent({ props: { value: { type: String, default: '' }, label: { type: String, default: '' } }, template: '<option :value="value">{{ label }}</option>' })
const input = defineComponent({ props: { modelValue: { type: [String, Number], default: '' }, disabled: Boolean }, emits: ['update:modelValue'], template: `<input :value="modelValue" :disabled="disabled" @input="$emit('update:modelValue', $event.target.value)" />` })
const number = defineComponent({ props: { modelValue: { type: [String, Number], default: '' }, disabled: Boolean }, emits: ['update:modelValue'], template: `<input type="number" :value="modelValue" :disabled="disabled" @input="$emit('update:modelValue', Number($event.target.value))" />` })
function render(permissions = ['finance:view','finance:invoice','finance:create','finance:post','master:view']) {
 const pinia=createPinia();useAuthStore(pinia).user={id:'u',username:'u',displayName:'u',organizationId:'o',organizationName:'o',departmentId:null,dataScope:'ALL',permissions,roles:['CUSTOM'],mustChangePassword:false}
 return mount(Panel,{global:{plugins:[pinia,createI18n({legacy:false,locale:'en-US',messages:{'en-US':en}})],directives:{loading:{}},stubs:{ElCard:slot,ElTabs:slot,ElTabPane:slot,ElTable:table,ElTableColumn:column,ElButton:button,ElAlert:slot,ElDatePicker:true,ElDialog:dialog,ElTag:true,ElOption:option,ElSelect:select,ElFormItem:slot,ElInput:input,ElInputNumber:number,ElForm:slot}}})
}
type Wrapper=ReturnType<typeof render>
const click=async(w:Wrapper,label:string)=>{await w.findAll('button').find(b=>b.text()===label)!.trigger('click');await flushPromises()}
async function invoice(w:Wrapper) { await click(w,'New formal invoice');await w.find('.editor select').setValue('SALES_INVOICE');await w.findAll('.editor select')[1]!.setValue('customer');await w.find('.editor input:not([type=number])').setValue('Services');await w.findAll('.editor input[type=number]')[1]!.setValue('30') }
async function payment(w:Wrapper) { await click(w,'New receipt / payment');await w.findAll('.editor select')[1]!.setValue('customer');await w.find('.editor input[type=number]').setValue('30') }
beforeEach(()=>{
 vi.resetAllMocks();vi.mocked(api.getFinanceDashboard).mockResolvedValue({receivables:0,payables:0,cash:0,revenue:0,expense:0,netIncome:0,trialDebit:0,trialCredit:0,unmatchedBankLines:0,matchExceptions:0});vi.mocked(api.listFinanceInvoices).mockResolvedValue([]);vi.mocked(api.listFinancePayments).mockResolvedValue([]);vi.mocked(api.listBankStatementLines).mockResolvedValue([])
 vi.mocked(master.getOrganizationSettings).mockResolvedValue({id:'o',name:'o',baseCurrencyCode:'CNY',timezone:'Asia/Shanghai',approvalThreshold:100,defaultTaxRate:0,active:true})
 vi.mocked(master.listMasterData).mockImplementation(async(resource)=>({content:[{id:resource==='customers'?'customer':'supplier',code:resource,name:resource,active:true}],page:0,size:100,totalElements:1,totalPages:1}))
})
it('creates invoices and payments in the displayed organization base currency',async()=>{ const w=render();await flushPromises();await invoice(w);expect(w.text()).toContain('CNY');await click(w,'Save');expect(api.createFinanceInvoice).toHaveBeenCalledWith(expect.objectContaining({currencyCode:'CNY',exchangeRate:1,partyId:'customer'}));await payment(w);await click(w,'Save');expect(api.createFinancePayment).toHaveBeenCalledWith(expect.objectContaining({currencyCode:'CNY',exchangeRate:1,partyId:'customer'})) })
it('blocks empty forms and clears customer selection when changing to supplier',async()=>{const w=render();await flushPromises();await click(w,'New formal invoice');await click(w,'Save');expect(api.createFinanceInvoice).not.toHaveBeenCalled();await w.findAll('.editor select')[1]!.setValue('customer');await w.find('.editor select').setValue('SUPPLIER_INVOICE');expect((w.findAll('.editor select')[1]!.element as HTMLSelectElement).value).toBe('');await click(w,'Save');expect(api.createFinanceInvoice).not.toHaveBeenCalled()})
it('blocks writes when organization currency cannot load',async()=>{vi.mocked(master.getOrganizationSettings).mockRejectedValue(new Error('unavailable'));const w=render();await flushPromises();await invoice(w);await click(w,'Save');expect(api.createFinanceInvoice).not.toHaveBeenCalled()})
it('submits once while pending and retains input after failure for explicit retry',async()=>{let reject!:(e:Error)=>void;vi.mocked(api.createFinancePayment).mockImplementationOnce(()=>new Promise((_,r)=>{reject=r}));const w=render();await flushPromises();await payment(w);await click(w,'Save');await click(w,'Save');expect(api.createFinancePayment).toHaveBeenCalledTimes(1);reject(new Error('unavailable'));await flushPromises();expect(w.find('.editor').exists()).toBe(true);expect((w.find('.editor input[type=number]').element as HTMLInputElement).value).toBe('30');await click(w,'Save');expect(api.createFinancePayment).toHaveBeenCalledTimes(2)})
it('does not load parties without master permission or expose creation controls',async()=>{const w=render(['finance:view']);await flushPromises();expect(master.listMasterData).not.toHaveBeenCalled();expect(w.text()).not.toContain('New formal invoice');expect(w.text()).not.toContain('New receipt / payment')})

it('clears receipt customer after switching to payment and starts a clean form on reopen',async()=>{const w=render();await flushPromises();await payment(w);await w.find('.editor select').setValue('PAYMENT');expect((w.findAll('.editor select')[1]!.element as HTMLSelectElement).value).toBe('');await click(w,'Save');expect(api.createFinancePayment).not.toHaveBeenCalled();await click(w,'Cancel');await click(w,'New receipt / payment');expect((w.find('.editor select').element as HTMLSelectElement).value).toBe('RECEIPT');expect((w.findAll('.editor select')[1]!.element as HTMLSelectElement).value).toBe('')})
it('guards zero amount and tax above 100 before making any invoice request',async()=>{const w=render();await flushPromises();await invoice(w);await w.findAll('.editor input[type=number]')[2]!.setValue('101');await click(w,'Save');expect(api.createFinanceInvoice).not.toHaveBeenCalled();await w.findAll('.editor input[type=number]')[2]!.setValue('0');await w.findAll('.editor input[type=number]')[1]!.setValue('0');await click(w,'Save');expect(api.createFinanceInvoice).not.toHaveBeenCalled()})
it('posts the displayed version once and notifies the parent after success',async()=>{let resolve!:()=>void;vi.mocked(api.postFinanceInvoice).mockImplementationOnce(()=>new Promise(r=>{resolve=()=>r({} as api.FinanceInvoice)}));const date=new Date().toISOString().slice(0,10);vi.mocked(api.listFinanceInvoices).mockResolvedValue([{id:'one',status:'DRAFT',version:7,accountingDate:date}] as api.FinanceInvoice[]);const w=render();await flushPromises();await click(w,'Post');await click(w,'Post');expect(api.postFinanceInvoice).toHaveBeenCalledTimes(1);expect(api.postFinanceInvoice).toHaveBeenCalledWith(expect.objectContaining({id:'one',version:7}));resolve();await flushPromises();expect(w.emitted('posted')).toHaveLength(1)})
it('offers settlement management on posted receipts including fully allocated ones',async()=>{const date=new Date().toISOString().slice(0,10);vi.mocked(api.listFinancePayments).mockResolvedValue([{id:'paid',number:'RC-paid',paymentType:'RECEIPT',partyType:'CUSTOMER',partyId:'customer',status:'POSTED',allocationStatus:'ALLOCATED',currencyCode:'CNY',version:1,amount:30,allocatedAmount:30,allocations:[],accountingDate:date}] as api.FinancePayment[]);const w=render(['finance:view','finance:allocate']);await flushPromises();expect(w.findAll('button').some(b=>b.text()==='Manage allocations')).toBe(true)})
