/* eslint-disable vue/one-component-per-file -- Focused editor stubs. */
import { mount, flushPromises } from '@vue/test-utils'
import { computed, defineComponent, h, inject, provide, type Ref } from 'vue'
import { createPinia } from 'pinia'
import { createI18n } from 'vue-i18n'
import { beforeEach, expect, it, vi } from 'vitest'
import { useAuthStore } from '@/stores/auth'
import Dialog from '@/components/finance/FinanceAllocationDialog.vue'
import en from '@/i18n/locales/en-US'
import * as api from '@/api/finance-v2'
vi.mock('@/api/finance-v2', () => ({ listFinanceInvoices: vi.fn(), listFinancePayments: vi.fn(), allocateFinancePayment: vi.fn(), reverseFinanceAllocation: vi.fn() }))
const slot = defineComponent({ template: '<div><slot /></div>' })
const button = defineComponent({ props: { disabled: Boolean, loading: Boolean }, template: '<button :disabled="disabled || loading"><slot /></button>' })
const dialog = defineComponent({ props: { modelValue: Boolean }, template: '<section v-if="modelValue"><slot /><slot name="footer" /></section>' })
const select = defineComponent({ props: { modelValue: { type: String, default: '' } }, emits: ['update:modelValue','change'], template: `<select :value="modelValue" @change="$emit('update:modelValue', $event.target.value); $emit('change')"><option value=""></option><slot /></select>` })
const option = defineComponent({ props: { value: { type: String, default: '' }, label: { type: String, default: '' } }, template: '<option :value="value">{{ label }}</option>' })
const number = defineComponent({ props: { modelValue: { type: Number, default: 0 }, max: { type: Number, default: 0 } }, emits: ['update:modelValue'], template: `<input type="number" :max="max" :value="modelValue" @input="$emit('update:modelValue', Number($event.target.value))" />` })
const text = defineComponent({ props: { modelValue: { type: String, default: '' } }, emits: ['update:modelValue'], template: `<textarea :value="modelValue" @input="$emit('update:modelValue', $event.target.value)" />` })
const alert = defineComponent({ props: { title: { type: String, default: '' } }, template: '<p role="alert">{{ title }}</p>' })
const table = defineComponent({ props: { data: { type: Array, default: () => [] } }, setup(props,{slots}) { provide('rows',computed(()=>props.data));return ()=>h('div',slots.default?.()) } })
const column = defineComponent({ setup(_,{slots}) { const rows=inject<Ref<api.FinanceAllocation[]>>('rows')!;return ()=>h('div',rows.value.flatMap(row=>slots.default?.({row})??[])) } })
const payment = (patch: Partial<api.FinancePayment> = {}): api.FinancePayment => ({ id:'payment',number:'RC-1',paymentType:'RECEIPT',partyType:'CUSTOMER',partyId:'customer',status:'POSTED',allocationStatus:'UNALLOCATED',accountingDate:'2026-10-05',currencyCode:'CNY',amount:30,allocatedAmount:0,version:1,allocations:[],...patch })
const invoice = (patch: Partial<api.FinanceInvoice> = {}): api.FinanceInvoice => ({ id:'invoice',number:'SI-1',documentType:'SALES_INVOICE',partyType:'CUSTOMER',partyId:'customer',status:'POSTED',settlementStatus:'UNPAID',currencyCode:'CNY',totalAmount:30,allocatedAmount:0,creditedAmount:0,accountingDate:'2025-01-01',dueDate:'2025-02-01',matchStatus:'NOT_REQUIRED',version:1,...patch })
const allocation = (patch: Partial<api.FinanceAllocation> = {}): api.FinanceAllocation => ({id:'allocation',paymentId:'payment',invoiceId:'invoice',amount:10,baseAmount:10,realizedExchangeDifference:0,status:'ACTIVE',allocatedAt:'2026-10-05T12:00:00',...patch})
function render(permissions=['finance:view','finance:allocate'], scope: 'ALL' | 'SELF' = 'ALL') {
 const pinia=createPinia();useAuthStore(pinia).user={id:'u',username:'u',displayName:'u',organizationId:'o',organizationName:'o',departmentId:null,dataScope:scope,permissions,roles:['CUSTOM'],mustChangePassword:false}
 return mount(Dialog,{props:{modelValue:true,paymentId:'payment'},global:{plugins:[pinia,createI18n({legacy:false,locale:'en-US',messages:{'en-US':en}})],directives:{loading:{}},stubs:{ElDialog:dialog,ElButton:button,ElAlert:alert,ElForm:slot,ElFormItem:slot,ElSelect:select,ElOption:option,ElInputNumber:number,ElInput:text,ElTable:table,ElTableColumn:column}}})
}
type Wrapper = ReturnType<typeof render>
async function click(w:Wrapper,label:string) {await w.findAll('button').find(b=>b.text()===label)!.trigger('click');await flushPromises()}
async function choose(w:Wrapper) {await w.find('select').setValue('invoice');await flushPromises()}
beforeEach(()=>{vi.resetAllMocks();vi.mocked(api.listFinancePayments).mockResolvedValue([payment()]);vi.mocked(api.listFinanceInvoices).mockResolvedValue([invoice()]);vi.mocked(api.allocateFinancePayment).mockResolvedValue(allocation());vi.mocked(api.reverseFinanceAllocation).mockResolvedValue(allocation({status:'REVERSED'}))})
it('loads current documents across accounting dates and limits amount by credit and payment balance',async()=>{
 vi.mocked(api.listFinancePayments).mockResolvedValue([payment({allocatedAmount:18})]);vi.mocked(api.listFinanceInvoices).mockResolvedValue([invoice({totalAmount:30,allocatedAmount:5,creditedAmount:10}),invoice({id:'other-party',number:'Wrong party',partyId:'other'}),invoice({id:'fx',number:'Wrong currency',currencyCode:'USD'}),invoice({id:'draft',number:'Draft',status:'DRAFT'}),invoice({id:'credit',number:'Credit note',documentType:'CUSTOMER_CREDIT'}),invoice({id:'settled',number:'Settled',allocatedAmount:30})]);const w=render();await flushPromises();expect(w.findAll('option')).toHaveLength(2);expect(w.text()).toContain('SI-1');expect(w.text()).not.toContain('Wrong party');await choose(w);expect((w.find('input').element as HTMLInputElement).value).toBe('12');expect(w.find('input').attributes('max')).toBe('12');await w.find('input').setValue('13');await click(w,'Allocate');expect(api.allocateFinancePayment).not.toHaveBeenCalled()
})
it('supports supplier payments with supplier invoices only',async()=>{vi.mocked(api.listFinancePayments).mockResolvedValue([payment({paymentType:'PAYMENT',partyType:'SUPPLIER',partyId:'supplier'})]);vi.mocked(api.listFinanceInvoices).mockResolvedValue([invoice(),invoice({id:'supplier-invoice',number:'PI-1',documentType:'SUPPLIER_INVOICE',partyType:'SUPPLIER',partyId:'supplier'})]);const w=render();await flushPromises();expect(w.text()).toContain('PI-1');expect(w.text()).not.toContain('SI-1');await w.find('select').setValue('supplier-invoice');await click(w,'Allocate');expect(api.allocateFinancePayment).toHaveBeenCalledWith('payment','supplier-invoice',30)})
it('refreshes remaining amounts after partial and full allocation without replaying the write',async()=>{
 vi.mocked(api.allocateFinancePayment).mockImplementation(async(_p,_i,amount)=>{const total=amount===10?10:30;vi.mocked(api.listFinancePayments).mockResolvedValue([payment({allocatedAmount:total,allocations:[allocation({amount:total})]})]);vi.mocked(api.listFinanceInvoices).mockResolvedValue([invoice({allocatedAmount:total})]);return allocation({amount})});const w=render();await flushPromises();await choose(w);await w.find('input').setValue('10');await click(w,'Allocate');expect(api.allocateFinancePayment).toHaveBeenLastCalledWith('payment','invoice',10);expect(w.text()).toContain('20.00');await choose(w);await click(w,'Allocate');expect(api.allocateFinancePayment).toHaveBeenLastCalledWith('payment','invoice',20);expect(api.allocateFinancePayment).toHaveBeenCalledTimes(2);expect(w.findAll('option')).toHaveLength(1);expect(w.text()).toContain('Reverse allocation');expect(w.emitted('changed')).toHaveLength(2)
})
it('blocks zero, negative and empty amounts and prevents repeated pending writes',async()=>{let resolve!:(a:api.FinanceAllocation)=>void;vi.mocked(api.allocateFinancePayment).mockImplementationOnce(()=>new Promise(r=>{resolve=r}));const w=render();await flushPromises();await choose(w);for(const amount of ['0','-1','']){await w.find('input').setValue(amount);await click(w,'Allocate')}expect(api.allocateFinancePayment).not.toHaveBeenCalled();await w.find('input').setValue('10');await click(w,'Allocate');await click(w,'Allocate');expect(api.allocateFinancePayment).toHaveBeenCalledTimes(1);await click(w,'Close');expect(w.emitted('update:modelValue')).toBeUndefined();resolve(allocation());await flushPromises()})
it('reloads history after an uncertain failed write instead of automatically retrying',async()=>{vi.mocked(api.allocateFinancePayment).mockImplementation(async()=>{vi.mocked(api.listFinancePayments).mockResolvedValue([payment({allocatedAmount:10,allocations:[allocation()]})]);vi.mocked(api.listFinanceInvoices).mockResolvedValue([invoice({allocatedAmount:10})]);throw new Error('lost response')});const w=render();await flushPromises();await choose(w);await w.find('input').setValue('10');await click(w,'Allocate');expect(api.allocateFinancePayment).toHaveBeenCalledTimes(1);expect(w.text()).toContain('Check the refreshed balances');expect(w.text()).toContain('20.00');expect(w.text()).toContain('Active');expect(w.emitted('changed')).toHaveLength(1)})
it('requires a reason for reversal, keeps its retry key and reloads reversed records',async()=>{vi.mocked(api.listFinancePayments).mockResolvedValue([payment({allocatedAmount:10,allocations:[allocation()]})]);vi.mocked(api.listFinanceInvoices).mockResolvedValue([invoice({allocatedAmount:10})]);vi.mocked(api.reverseFinanceAllocation).mockRejectedValueOnce(new Error('unavailable')).mockImplementationOnce(async()=>{vi.mocked(api.listFinancePayments).mockResolvedValue([payment({allocations:[allocation({status:'REVERSED'})]})]);vi.mocked(api.listFinanceInvoices).mockResolvedValue([invoice()]);return allocation({status:'REVERSED'})});const w=render();await flushPromises();await click(w,'Reverse allocation');await w.find('textarea').setValue('   ');await click(w,'Confirm reversal');expect(api.reverseFinanceAllocation).not.toHaveBeenCalled();await w.find('textarea').setValue('  Correct allocation  ');await click(w,'Confirm reversal');await click(w,'Confirm reversal');const calls=vi.mocked(api.reverseFinanceAllocation).mock.calls;expect(calls).toHaveLength(2);expect(calls[0]).toEqual(calls[1]);expect(calls[0]![1]).toBe('Correct allocation');expect(w.text()).toContain('Reversed');expect(w.text()).toContain('30.00');expect(w.findAll('button').some(b=>b.text()==='Reverse allocation')).toBe(false)})
it('blocks access without both permissions or with row-scoped finance permission',async()=>{for(const [permissions,scope] of [[['finance:view'],'ALL'],[['finance:allocate'],'ALL'],[['finance:view','finance:allocate'],'SELF']] as const){const w=render([...permissions],scope);await flushPromises();expect(api.listFinancePayments).not.toHaveBeenCalled();expect(api.listFinanceInvoices).not.toHaveBeenCalled();w.unmount()}})
it('blocks mutations when current documents fail to load and permits explicit reload',async()=>{vi.mocked(api.listFinanceInvoices).mockRejectedValueOnce(new Error('unavailable'));const w=render();await flushPromises();expect(w.text()).toContain('Unable to load current settlement data');expect(w.find('select').exists()).toBe(false);await click(w,'Reload');await choose(w);expect(w.find('input').attributes('max')).toBe('30')})
it('retains reversed history but never offers reversal twice',async()=>{vi.mocked(api.listFinancePayments).mockResolvedValue([payment({allocations:[allocation({status:'REVERSED'})]})]);const w=render();await flushPromises();expect(w.text()).toContain('Reversed');expect(w.findAll('button').some(b=>b.text()==='Reverse allocation')).toBe(false)})
it('rejects drafts and refunds and clears late reads after close',async()=>{for(const row of [payment({status:'DRAFT'}),payment({paymentType:'CUSTOMER_REFUND'})]){vi.mocked(api.listFinancePayments).mockResolvedValue([row]);const w=render();await flushPromises();expect(w.find('select').exists()).toBe(false);w.unmount()}let resolve!:(rows:api.FinancePayment[])=>void;vi.mocked(api.listFinancePayments).mockImplementationOnce(()=>new Promise(r=>{resolve=r}));const w=render();await w.setProps({modelValue:false});resolve([payment()]);await flushPromises();expect(w.text()).not.toContain('RC-1');expect(api.allocateFinancePayment).not.toHaveBeenCalled()})
