/* eslint-disable vue/one-component-per-file -- UI stubs for focused form behavior. */
import { mount, flushPromises } from '@vue/test-utils'
import { computed, defineComponent, h, inject, provide, type Ref } from 'vue'
import { createPinia } from 'pinia'
import { createI18n } from 'vue-i18n'
import { beforeEach, expect, it, vi } from 'vitest'
import { useAuthStore } from '@/stores/auth'
import Panel from '@/components/finance/FinanceClosurePanel.vue'
import BankDialog from '@/components/finance/BankStatementDialog.vue'
import en from '@/i18n/locales/en-US'
import * as api from '@/api/finance-v2'
import * as master from '@/api/master-data'
vi.mock('@/api/finance-v2', () => ({ getFinanceDashboard: vi.fn(), listFinanceInvoices: vi.fn(), listFinancePayments: vi.fn(), listBankStatementLines: vi.fn(), listBankReconciliations: vi.fn().mockResolvedValue([]), reconcileBankStatement: vi.fn(), reverseBankReconciliation: vi.fn(), listFinanceBankAccounts: vi.fn().mockResolvedValue([]), importBankStatement: vi.fn(), createFinanceInvoice: vi.fn(), createFinancePayment: vi.fn(), postFinanceInvoice: vi.fn(), postFinancePayment: vi.fn(), allocateFinancePayment: vi.fn(), reverseFinanceAllocation: vi.fn() }))
vi.mock('@/api/master-data', () => ({ listMasterData: vi.fn(), getOrganizationSettings: vi.fn() }))
const table = defineComponent({ props: { data: { type: Array, default: () => [] } }, setup(props, { slots }) { provide('rows', computed(() => props.data)); return () => h('div', slots.default?.()) } })
const column = defineComponent({ setup(_, { slots }) { const rows = inject<Ref<api.FinanceInvoice[]>>('rows')!; return () => h('div', rows.value.flatMap(row => slots.default?.({ row }) ?? [])) } })
const slot = defineComponent({ template: '<div><slot /></div>' })
const dialog = defineComponent({ props: { modelValue: Boolean }, template: '<section v-if="modelValue" class="editor"><slot /><slot name="footer" /></section>' })
const button = defineComponent({ props: { disabled: Boolean, loading: Boolean }, template: '<button :disabled="disabled || loading"><slot /></button>' })
const select = defineComponent({ props: { modelValue: { type: [String, Number], default: '' }, disabled: Boolean }, emits: ['update:modelValue','change'], template: `<select :value="modelValue" :disabled="disabled" @change="$emit('update:modelValue', $event.target.value); $emit('change', $event.target.value)"><option value=""></option><slot /></select>` })
const option = defineComponent({ props: { value: { type: String, default: '' }, label: { type: String, default: '' } }, template: '<option :value="value">{{ label }}</option>' })
const input = defineComponent({ props: { modelValue: { type: [String, Number], default: '' }, disabled: Boolean }, emits: ['update:modelValue'], template: `<input :value="modelValue" :disabled="disabled" @input="$emit('update:modelValue', $event.target.value)" />` })
const number = defineComponent({ props: { modelValue: { type: [String, Number], default: '' }, disabled: Boolean }, emits: ['update:modelValue'], template: `<input type="number" :value="modelValue" :disabled="disabled" @input="$emit('update:modelValue', Number($event.target.value))" />` })
function render(permissions = ['finance:view','finance:invoice','finance:create','finance:post','master:view']) {
 const pinia=createPinia();useAuthStore(pinia).user={id:'u',username:'u',displayName:'u',organizationId:'o',organizationName:'o',departmentId:null,dataScope:'ALL',permissions,roles:['CUSTOM'],mustChangePassword:false}
 return mount(Panel,{global:{plugins:[pinia,createI18n({legacy:false,locale:'en-US',messages:{'en-US':en}})],directives:{loading:{}},stubs:{ElCard:slot,ElTabs:slot,ElTabPane:slot,ElTable:table,ElTableColumn:column,ElButton:button,ElAlert:slot,ElDatePicker:true,ElDialog:dialog,ElTag:true,ElOption:option,ElSelect:select,ElFormItem:slot,ElInput:input,ElInputNumber:number,ElForm:slot}}})
}
type Wrapper=ReturnType<typeof render>
const click=async(w:Wrapper,label:string)=>{await w.findAll('button').find(b=>b.text()===label)!.trigger('click');await flushPromises()}
async function invoice(w:Wrapper) { await click(w,'New formal invoice');await w.find('.editor select').setValue('SALES_INVOICE');await w.findAll('.editor select')[1]!.setValue('customer');await w.find('.editor input:not([type=number])').setValue('Services');await w.findAll('.editor input[type=number]')[1]!.setValue('30') }
async function payment(w:Wrapper) { await click(w,'New receipt / payment');await w.findAll('.editor select')[1]!.setValue('customer');await w.find('.editor input[type=number]').setValue('30') }
beforeEach(()=>{
 vi.resetAllMocks();vi.mocked(api.listFinanceBankAccounts).mockResolvedValue([]);vi.mocked(api.getFinanceDashboard).mockResolvedValue({receivables:0,payables:0,cash:0,revenue:0,expense:0,netIncome:0,trialDebit:0,trialCredit:0,unmatchedBankLines:0,matchExceptions:0});vi.mocked(api.listFinanceInvoices).mockResolvedValue([]);vi.mocked(api.listFinancePayments).mockResolvedValue([]);vi.mocked(api.listBankStatementLines).mockResolvedValue([])
 vi.mocked(master.getOrganizationSettings).mockResolvedValue({id:'o',name:'o',baseCurrencyCode:'CNY',timezone:'Asia/Shanghai',approvalThreshold:100,defaultTaxRate:0,active:true})
 vi.mocked(master.listMasterData).mockImplementation(async(resource)=>({content:[{id:resource==='customers'?'customer':'supplier',code:resource,name:resource,active:true}],page:0,size:100,totalElements:1,totalPages:1}))
})
it('creates invoices and payments in the displayed organization base currency',async()=>{ const w=render();await flushPromises();await invoice(w);expect(w.text()).toContain('CNY');await click(w,'Save');expect(api.createFinanceInvoice).toHaveBeenCalledWith(expect.objectContaining({currencyCode:'CNY',exchangeRate:1,partyId:'customer'}));await payment(w);await click(w,'Save');expect(api.createFinancePayment).toHaveBeenCalledWith(expect.objectContaining({currencyCode:'CNY',exchangeRate:1,partyId:'customer'})) })
it('blocks empty forms and clears customer selection when changing to supplier',async()=>{const w=render();await flushPromises();await click(w,'New formal invoice');await click(w,'Save');expect(api.createFinanceInvoice).not.toHaveBeenCalled();await w.findAll('.editor select')[1]!.setValue('customer');await w.find('.editor select').setValue('SUPPLIER_INVOICE');expect((w.findAll('.editor select')[1]!.element as HTMLSelectElement).value).toBe('');await click(w,'Save');expect(api.createFinanceInvoice).not.toHaveBeenCalled()})
it('blocks writes when organization currency cannot load',async()=>{vi.mocked(master.getOrganizationSettings).mockRejectedValue(new Error('unavailable'));const w=render();await flushPromises();await invoice(w);await click(w,'Save');expect(api.createFinanceInvoice).not.toHaveBeenCalled()})
it('submits once while pending and retains input after failure for explicit retry',async()=>{let reject!:(e:Error)=>void;vi.mocked(api.createFinancePayment).mockImplementationOnce(()=>new Promise((_,r)=>{reject=r}));const w=render();await flushPromises();await payment(w);await click(w,'Save');await click(w,'Save');expect(api.createFinancePayment).toHaveBeenCalledTimes(1);reject(new Error('unavailable'));await flushPromises();expect(w.find('.editor').exists()).toBe(true);expect((w.find('.editor input[type=number]').element as HTMLInputElement).value).toBe('30');await click(w,'Save');expect(api.createFinancePayment).toHaveBeenCalledTimes(2)})
it('does not load parties without master permission or expose creation controls',async()=>{const w=render(['finance:view']);await flushPromises();expect(master.listMasterData).not.toHaveBeenCalled();expect(w.text()).not.toContain('New formal invoice');expect(w.text()).not.toContain('New receipt / payment')})

it('clears receipt customer after switching to payment and starts a clean form on reopen',async()=>{const w=render();await flushPromises();await payment(w);await w.find('.editor select').setValue('PAYMENT');expect((w.findAll('.editor select')[1]!.element as HTMLSelectElement).value).toBe('');await click(w,'Save');expect(api.createFinancePayment).not.toHaveBeenCalled();await click(w,'Cancel');await click(w,'New receipt / payment');expect((w.find('.editor select').element as HTMLSelectElement).value).toBe('RECEIPT');expect((w.findAll('.editor select')[1]!.element as HTMLSelectElement).value).toBe('')})
it('guards zero amount and tax above 100 before making any invoice request',async()=>{const w=render();await flushPromises();await invoice(w);await w.findAll('.editor input[type=number]')[2]!.setValue('101');await click(w,'Save');expect(api.createFinanceInvoice).not.toHaveBeenCalled();await w.findAll('.editor input[type=number]')[2]!.setValue('0');await w.findAll('.editor input[type=number]')[1]!.setValue('0');await click(w,'Save');expect(api.createFinanceInvoice).not.toHaveBeenCalled()})
it('posts the displayed version once and notifies the parent after success',async()=>{let resolve!:()=>void;vi.mocked(api.postFinanceInvoice).mockImplementationOnce(()=>new Promise(r=>{resolve=()=>r({} as api.FinanceInvoice)}));const date=new Date().toISOString().slice(0,10);vi.mocked(api.listFinanceInvoices).mockResolvedValue([{id:'one',status:'DRAFT',version:7,accountingDate:date}] as api.FinanceInvoice[]);const w=render();await flushPromises();await click(w,'Post');await click(w,'Post');expect(api.postFinanceInvoice).toHaveBeenCalledTimes(1);expect(api.postFinanceInvoice).toHaveBeenCalledWith(expect.objectContaining({id:'one',version:7}));resolve();await flushPromises();expect(w.emitted('posted')).toHaveLength(1)})
it('offers settlement management on posted receipts including fully allocated ones',async()=>{const date=new Date().toISOString().slice(0,10);vi.mocked(api.listFinancePayments).mockResolvedValue([{id:'paid',number:'RC-paid',paymentType:'RECEIPT',partyType:'CUSTOMER',partyId:'customer',status:'POSTED',allocationStatus:'ALLOCATED',currencyCode:'CNY',version:1,amount:30,allocatedAmount:30,allocations:[],accountingDate:date}] as api.FinancePayment[]);const w=render(['finance:view','finance:allocate']);await flushPromises();expect(w.findAll('button').some(b=>b.text()==='Manage allocations')).toBe(true)})

it('selects a base currency bank for payment and keeps foreign accounts out of the picker',async()=>{vi.mocked(api.listFinanceBankAccounts).mockResolvedValue([{id:'bank',code:'B1',name:'Bank',currencyCode:'CNY'},{id:'fx',code:'FX',name:'Foreign',currencyCode:'USD'}]);const w=render();await flushPromises();await payment(w);const picker=w.findAll('.editor select')[2]!;expect(picker.text()).toContain('B1');expect(picker.text()).not.toContain('FX');await picker.setValue('bank');await click(w,'Save');expect(api.createFinancePayment).toHaveBeenCalledWith(expect.objectContaining({bankAccountId:'bank'}))})
it('keeps cash available when bank accounts cannot be loaded',async()=>{vi.mocked(api.listFinanceBankAccounts).mockRejectedValue(new Error('offline'));const w=render();await flushPromises();await payment(w);expect(w.findAll('.editor select')[2]!.attributes('disabled')).toBeDefined();await click(w,'Save');expect(api.createFinancePayment).toHaveBeenCalledWith(expect.objectContaining({bankAccountId:undefined}))})
function renderBank(permissions=['finance:view','finance:bank'],scope:'ALL'|'SELF'|'DEPARTMENT'|'ASSIGNED'='ALL') { const pinia=createPinia();useAuthStore(pinia).user={id:'u',username:'u',displayName:'u',organizationId:'o',organizationName:'o',departmentId:null,dataScope:scope,permissions,roles:[],mustChangePassword:false};return mount(BankDialog,{props:{modelValue:true},global:{plugins:[pinia,createI18n({legacy:false,locale:'en-US',messages:{'en-US':en}})],stubs:{ElDialog:dialog,ElButton:button,ElAlert:defineComponent({props:{title:{type:String,default:''}},template:'<p>{{ title }}</p>'}),ElSelect:select,ElOption:option,ElForm:slot,ElFormItem:slot,ElInput:input,ElInputNumber:number}}}) }
type BankWrapper=ReturnType<typeof renderBank>
const bankClick=async(w:BankWrapper,label:string)=>{await w.findAll('button').find(b=>b.text()===label)!.trigger('click');await flushPromises()}
async function bankFields(w:BankWrapper,amount='30') {await w.find('select').setValue('bank');await w.find('input[type=date]').setValue('2026-10-05');await w.find('input[type=number]').setValue(amount);await w.find('input:not([type])').setValue('  bank-ref  ')}
const bankFixture=()=>vi.mocked(api.listFinanceBankAccounts).mockResolvedValue([{id:'bank',code:'B1',name:'Bank',currencyCode:'CNY'}])
it('records a signed statement using the selected account currency and trimmed reference',async()=>{bankFixture();const w=renderBank();await flushPromises();await bankFields(w,'-12');await bankClick(w,'Save statement');expect(api.importBankStatement).toHaveBeenCalledWith({bankAccountId:'bank',lines:[{transactionDate:'2026-10-05',amount:-12,currencyCode:'CNY',externalReference:'bank-ref'}]});expect(w.emitted('changed')).toHaveLength(1);expect(w.emitted('update:modelValue')).toEqual([[false]])})
it('blocks statement without bank, zero amount, blank reference or invalid date',async()=>{bankFixture();const w=renderBank();await flushPromises();await bankClick(w,'Save statement');await bankFields(w,'0');await bankClick(w,'Save statement');await w.find('input[type=number]').setValue('30');await w.find('input:not([type])').setValue(' ');await bankClick(w,'Save statement');await w.find('input:not([type])').setValue('ref');await w.find('input[type=date]').setValue('');await bankClick(w,'Save statement');expect(api.importBankStatement).not.toHaveBeenCalled()})
it('prevents repeated pending import and preserves failed form without automatically retrying',async()=>{bankFixture();let reject!:(e:Error)=>void;vi.mocked(api.importBankStatement).mockImplementationOnce(()=>new Promise((_r,j)=>{reject=j}));const w=renderBank();await flushPromises();await bankFields(w);await bankClick(w,'Save statement');await bankClick(w,'Save statement');await bankClick(w,'Close');expect(w.emitted('update:modelValue')).toBeUndefined();expect(api.importBankStatement).toHaveBeenCalledTimes(1);reject(new Error('lost response'));await flushPromises();expect(w.text()).toContain('Check the refreshed statement list');expect((w.find('input:not([type])').element as HTMLInputElement).value).toBe('  bank-ref  ');expect(w.emitted('changed')).toHaveLength(1)})
it('requires both finance permissions and organization-wide scope for statement entry',async()=>{for(const [permissions,scope] of [[['finance:view'],'ALL'],[['finance:bank'],'ALL'],[['finance:view','finance:bank'],'SELF']] as const){const w=renderBank([...permissions],scope);await flushPromises();expect(api.listFinanceBankAccounts).not.toHaveBeenCalled();await bankClick(w,'Save statement');expect(api.importBankStatement).not.toHaveBeenCalled();w.unmount()}})
it('blocks import on bank load failure and reloads only when requested',async()=>{vi.mocked(api.listFinanceBankAccounts).mockRejectedValueOnce(new Error('offline'));const w=renderBank();await flushPromises();expect(w.text()).toContain('Unable to load bank accounts');await bankClick(w,'Save statement');expect(api.importBankStatement).not.toHaveBeenCalled();bankFixture();await bankClick(w,'Reload');expect(w.find('select').text()).toContain('B1')})
it('resets bank statement form on reopening and ignores late account loads after close',async()=>{bankFixture();const w=renderBank();await flushPromises();await bankFields(w);await w.setProps({modelValue:false});await w.setProps({modelValue:true});await flushPromises();expect((w.find('select').element as HTMLSelectElement).value).toBe('');expect((w.find('input:not([type])').element as HTMLInputElement).value).toBe('');let resolve!:(v:api.FinanceBankAccount[])=>void;vi.mocked(api.listFinanceBankAccounts).mockImplementationOnce(()=>new Promise(r=>{resolve=r}));await bankClick(w,'Reload');await w.setProps({modelValue:false});resolve([{id:'late',code:'Late',name:'Late',currencyCode:'CNY'}]);await flushPromises();expect(w.text()).not.toContain('Late')})

it('shows bank identity and currency next to signed statement amounts',async()=>{vi.mocked(api.listFinanceBankAccounts).mockResolvedValue([{id:'bank',code:'B1',name:'Bank',currencyCode:'CNY'}]);const d=new Date();const date=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;vi.mocked(api.listBankStatementLines).mockResolvedValue([{id:'line',bankAccountId:'bank',transactionDate:date,amount:-12,currencyCode:'CNY',externalReference:'ref',reconciliationStatus:'UNMATCHED'}]);const w=render();await flushPromises();expect(w.text()).toContain('B1 · Bank');expect(w.text()).toContain('-12.00 CNY')})

it('renders statement inputs after account loading completes',async()=>{let resolve!:(v:api.FinanceBankAccount[])=>void;vi.mocked(api.listFinanceBankAccounts).mockImplementationOnce(()=>new Promise(r=>{resolve=r}));const w=renderBank();expect(w.find('input[type=number]').exists()).toBe(false);resolve([{id:'bank',code:'B1',name:'Bank',currencyCode:'CNY'}]);await flushPromises();expect(w.find('input[type=number]').exists()).toBe(true)})
