/* eslint-disable vue/one-component-per-file -- Focused editor stubs. */
import { mount, flushPromises } from '@vue/test-utils'
import { defineComponent } from 'vue'
import { createPinia } from 'pinia'
import { createI18n } from 'vue-i18n'
import { beforeEach, expect, it, vi } from 'vitest'
import { useAuthStore } from '@/stores/auth'
import Dialog from '@/components/finance/ForeignDocumentDialog.vue'
import en from '@/i18n/locales/en-US'
import * as api from '@/api/finance-v2'
vi.mock('@/api/finance-v2', () => ({ listFinanceBankAccounts: vi.fn(), createFinanceInvoice: vi.fn(), createFinancePayment: vi.fn() }))
import * as master from '@/api/master-data'
vi.mock('@/api/master-data', () => ({ getOrganizationSettings: vi.fn(), listMasterData: vi.fn() }))
const slot = defineComponent({ template: '<div><slot /></div>' })
const button = defineComponent({ props: { disabled: Boolean, loading: Boolean }, template: '<button :disabled="disabled || loading"><slot /></button>' })
const dialog = defineComponent({ props: { modelValue: Boolean }, template: '<section v-if="modelValue"><slot /><slot name="footer" /></section>' })
const select = defineComponent({ props: { modelValue: { type: String, default: '' } }, emits: ['update:modelValue','change'], template: `<select :value="modelValue" @change="$emit('update:modelValue', $event.target.value); $emit('change')"><option value=""></option><slot /></select>` })
const option = defineComponent({ props: { value: { type: String, default: '' }, label: { type: String, default: '' } }, template: '<option :value="value">{{ label }}</option>' })
const alert = defineComponent({ props: { title: { type: String, default: '' } }, template: '<p role="alert">{{ title }}</p>' })
const number = defineComponent({ props: { modelValue: { type: Number, default: 1 } }, emits: ['update:modelValue'], template: `<input type="number" :value="modelValue" @input="$emit('update:modelValue', Number($event.target.value))" />` })
const input = defineComponent({ props:{modelValue:{type:String,default:''}},emits:['update:modelValue'],template:`<input :value="modelValue" @input="$emit('update:modelValue',$event.target.value)" />` })
function render(permissions=['finance:view','master:view','finance:invoice','finance:create'],scope:'ALL'|'SELF'='ALL') {const pinia=createPinia();useAuthStore(pinia).user={id:'u',username:'u',displayName:'u',organizationId:'o',organizationName:'o',departmentId:null,dataScope:scope,permissions,roles:[],mustChangePassword:false};return mount(Dialog,{props:{modelValue:true},global:{plugins:[pinia,createI18n({legacy:false,locale:'en-US',messages:{'en-US':en}})],stubs:{ElDialog:dialog,ElButton:button,ElAlert:alert,ElForm:slot,ElFormItem:slot,ElSelect:select,ElOption:option,ElInputNumber:number,ElInput:input,ElDatePicker:input}}})}
type Wrapper=ReturnType<typeof render>
async function click(w:Wrapper,label:string){await w.findAll('button').find(b=>b.text()===label)!.trigger('click');await flushPromises()}
async function fields(w:Wrapper,kind='SALES_INVOICE',rate='7.2'){await w.findAll('select')[0]!.setValue(kind);await w.findAll('select')[1]!.setValue(['SALES_INVOICE','RECEIPT'].includes(kind)?'customer':'supplier');await w.findAll('select')[2]!.setValue('USD');await w.findAll('input[type=number]')[0]!.setValue(rate);if(kind.endsWith('INVOICE')){await w.find('input:not([type])').setValue('FX ordinary');await w.findAll('input[type=number]')[2]!.setValue('100')}else{await w.findAll('input[type=number]')[1]!.setValue('100')}}
beforeEach(()=>{vi.clearAllMocks();vi.mocked(api.listFinanceBankAccounts).mockReset().mockResolvedValue([{id:'cny',code:'C',name:'CNY Bank',currencyCode:'CNY'},{id:'usd',code:'U',name:'USD Bank',currencyCode:'USD'}]);vi.mocked(api.createFinanceInvoice).mockReset().mockResolvedValue({} as api.FinanceInvoice);vi.mocked(api.createFinancePayment).mockReset().mockResolvedValue({} as api.FinancePayment);vi.mocked(master.getOrganizationSettings).mockReset().mockResolvedValue({baseCurrencyCode:'CNY'} as Awaited<ReturnType<typeof master.getOrganizationSettings>>);vi.mocked(master.listMasterData).mockReset().mockImplementation(async(resource)=>({content:resource==='currencies'?[{id:'base',code:'CNY',name:'Yuan',active:true},{id:'fx',code:'USD',name:'Dollar',active:true},{id:'off',code:'EUR',active:false}]:[{id:resource==='customers'?'customer':'supplier',code:'P',active:true}],page:0,size:100,totalElements:1,totalPages:1}))})
it('saves an FX invoice with explicit direction, rate, date and original currency',async()=>{const w=render();await flushPromises();await fields(w);expect(w.text()).toContain('1 USD = entered rate in CNY');expect(w.findAll('select')[2]!.findAll('option')).toHaveLength(2);await click(w,'Save');expect(api.createFinanceInvoice).toHaveBeenCalledWith(expect.objectContaining({documentType:'SALES_INVOICE',partyId:'customer',currencyCode:'USD',exchangeRate:7.2,exchangeRateDate:expect.stringMatching(/^\d{4}-\d{2}-\d{2}$/),lines:[expect.objectContaining({unitPrice:100,quantity:1})]}),expect.any(String));expect(api.createFinancePayment).not.toHaveBeenCalled();expect(w.emitted('update:modelValue')).toEqual([[false]])})
it('supports supplier invoices and receipts/payments with same-currency banks',async()=>{for(const kind of ['SUPPLIER_INVOICE','RECEIPT','PAYMENT']){const w=render();await flushPromises();await fields(w,kind,'7.3');if(!kind.endsWith('INVOICE')){expect(w.findAll('select')[3]!.text()).toContain('USD Bank');expect(w.findAll('select')[3]!.text()).not.toContain('CNY Bank');await w.findAll('select')[3]!.setValue('usd')}await click(w,'Save');if(kind.endsWith('INVOICE'))expect(api.createFinanceInvoice).toHaveBeenCalledWith(expect.objectContaining({documentType:kind,partyId:'supplier'}),expect.any(String));else expect(api.createFinancePayment).toHaveBeenCalledWith(expect.objectContaining({paymentType:kind,partyId:kind==='RECEIPT'?'customer':'supplier',currencyCode:'USD',exchangeRate:7.3,bankAccountId:'usd',amount:100}),expect.any(String));w.unmount()}})
it('requires a positive eight-decimal rate and a valid non-future date',async()=>{const w=render();await flushPromises();await fields(w,'SALES_INVOICE','0');await click(w,'Save');await w.find('input[type=number]').setValue('7.123456789');await click(w,'Save');await w.find('input[type=number]').setValue('7.12345678');await w.find('input[type=date]').setValue('2026-02-30');await click(w,'Save');await w.find('input[type=date]').setValue('2999-01-01');await click(w,'Save');expect(api.createFinanceInvoice).not.toHaveBeenCalled();await w.find('input[type=date]').setValue('2026-01-01');await click(w,'Save');expect(api.createFinanceInvoice).toHaveBeenCalledTimes(1)})
it('loads all master pages and fails closed on incomplete currencies or banks',async()=>{vi.mocked(master.listMasterData).mockImplementation(async(resource,_query,page)=>({content:resource==='currencies'?[{id:page?'usd':'base',code:page?'USD':'CNY',active:true}]:[{id:resource==='customers'?'customer':'supplier',code:'P',active:true}],page,size:100,totalElements:resource==='currencies'?2:1,totalPages:resource==='currencies'?2:1}));const w=render();await flushPromises();expect(master.listMasterData).toHaveBeenCalledWith('currencies','',1,100);await fields(w);vi.mocked(api.listFinanceBankAccounts).mockRejectedValueOnce(new Error('offline'));await click(w,'Reload');await click(w,'Save');expect(api.createFinanceInvoice).not.toHaveBeenCalled();expect(w.text()).toContain('Unable to load complete')})
it('resets rate and bank selection when switching currency',async()=>{vi.mocked(master.listMasterData).mockImplementation(async(resource)=>({content:resource==='currencies'?[{id:'usd',code:'USD',active:true},{id:'eur',code:'EUR',active:true}]:[{id:resource==='customers'?'customer':'supplier',code:'P',active:true}],page:0,size:100,totalElements:2,totalPages:1}));const w=render();await flushPromises();await fields(w,'RECEIPT');await w.findAll('select')[3]!.setValue('usd');await w.findAll('select')[2]!.setValue('EUR');expect((w.find('input[type=number]').element as HTMLInputElement).value).toBe('0');expect((w.findAll('select')[3]!.element as HTMLSelectElement).value).toBe('');await click(w,'Save');expect(api.createFinancePayment).not.toHaveBeenCalled()})
it('retains payment idempotency key on explicit retry and blocks pending close/duplicate save',async()=>{let reject!:(e:Error)=>void;vi.mocked(api.createFinancePayment).mockImplementationOnce(()=>new Promise((_r,j)=>{reject=j}));const w=render();await flushPromises();await fields(w,'RECEIPT');await click(w,'Save');await click(w,'Save');await click(w,'Close');expect(api.createFinancePayment).toHaveBeenCalledTimes(1);expect(w.emitted('update:modelValue')).toBeUndefined();reject(new Error('lost'));await flushPromises();await click(w,'Save');expect(vi.mocked(api.createFinancePayment).mock.calls[0]![1]).toBe(vi.mocked(api.createFinancePayment).mock.calls[1]![1])})
it('changes the request key for changed rate after uncertain save',async()=>{vi.mocked(api.createFinanceInvoice).mockRejectedValueOnce(new Error('lost'));const w=render();await flushPromises();await fields(w);await click(w,'Save');await w.find('input[type=number]').setValue('7.3');await click(w,'Save');expect(vi.mocked(api.createFinanceInvoice).mock.calls[0]![1]).not.toBe(vi.mocked(api.createFinanceInvoice).mock.calls[1]![1])})
it('requires view/master/create permission and ALL scope; respects separate invoice/payment permissions',async()=>{for(const [p,s] of [[['finance:invoice','finance:view'],'ALL'],[['finance:invoice','master:view'],'ALL'],[['finance:invoice','finance:view','master:view'],'SELF']] as const){const w=render([...p],s);await flushPromises();expect(master.listMasterData).not.toHaveBeenCalled();w.unmount()}const w=render(['finance:view','master:view','finance:create']);await flushPromises();expect(w.findAll('select')[0]!.text()).not.toContain('invoice');expect(w.findAll('select')[0]!.text()).toContain('Receipt')})
it('drops delayed master data on close and clears all inputs on reopen',async()=>{let resolve!:(v:Awaited<ReturnType<typeof master.getOrganizationSettings>>)=>void;vi.mocked(master.getOrganizationSettings).mockImplementationOnce(()=>new Promise(r=>{resolve=r}));const w=render();await w.setProps({modelValue:false});resolve({baseCurrencyCode:'CNY'} as Awaited<ReturnType<typeof master.getOrganizationSettings>>);await flushPromises();expect(w.find('select').exists()).toBe(false);await w.setProps({modelValue:true});await flushPromises();expect((w.findAll('select')[2]!.element as HTMLSelectElement).value).toBe('')})
