/* eslint-disable vue/one-component-per-file -- Focused editor stubs. */
import { mount, flushPromises } from '@vue/test-utils'
import { defineComponent } from 'vue'
import { createPinia } from 'pinia'
import { createI18n } from 'vue-i18n'
import { beforeEach, expect, it, vi } from 'vitest'
import { useAuthStore } from '@/stores/auth'
import Dialog from '@/components/finance/MatchExceptionDialog.vue'
import en from '@/i18n/locales/en-US'
import * as api from '@/api/finance-v2'
vi.mock('@/api/finance-v2', () => ({ getFinanceInvoice: vi.fn(), approveFinanceMatchException: vi.fn() }))
const slot = defineComponent({ template: '<div><slot /></div>' })
const button = defineComponent({ props: { disabled: Boolean, loading: Boolean }, template: '<button :disabled="disabled || loading"><slot /></button>' })
const dialog = defineComponent({ props: { modelValue: Boolean }, template: '<section v-if="modelValue"><slot /><slot name="footer" /></section>' })
const text = defineComponent({ props: { modelValue: { type: String, default: '' } }, emits: ['update:modelValue'], template: `<textarea :value="modelValue" @input="$emit('update:modelValue', $event.target.value)" />` })
const alert = defineComponent({ props: { title: { type: String, default: '' } }, template: '<p role="alert">{{ title }}</p>' })
const row=(patch:Partial<api.FinanceInvoiceDetail>={}):api.FinanceInvoiceDetail=>({id:'i',number:'PI-1',documentType:'SUPPLIER_INVOICE',partyType:'SUPPLIER',partyId:'supplier',status:'DRAFT',settlementStatus:'UNPAID',currencyCode:'CNY',totalAmount:12,allocatedAmount:0,creditedAmount:0,accountingDate:'2026-10-05',dueDate:'2026-11-05',matchStatus:'EXCEPTION',version:0,lines:[{id:'il',lineNo:1,description:'Part',quantity:1,unitPrice:12,taxRate:0,matchQuantityVariance:0,matchPriceVarianceRate:20,matchTaxVariance:0,sources:[{sourceType:'PURCHASE_RECEIPT_LINE',sourceId:'receipt',sourceLineId:'real-line',quantity:1,amount:12}]}],...patch})
function render(permissions=['finance:view','finance:match-exception'],scope:'ALL'|'SELF'='ALL'){const pinia=createPinia();useAuthStore(pinia).user={id:'u',username:'u',displayName:'u',organizationId:'o',organizationName:'o',departmentId:null,dataScope:scope,permissions,roles:[],mustChangePassword:false};return mount(Dialog,{props:{modelValue:true,invoiceId:'i'},global:{plugins:[pinia,createI18n({legacy:false,locale:'en-US',messages:{'en-US':en}})],stubs:{ElDialog:dialog,ElButton:button,ElAlert:alert,ElForm:slot,ElFormItem:slot,ElInput:text}}})}
type Wrapper=ReturnType<typeof render>
async function click(w:Wrapper,label:string){await w.findAll('button').find(b=>b.text()===label)!.trigger('click');await flushPromises()}
beforeEach(()=>{vi.clearAllMocks();vi.mocked(api.getFinanceInvoice).mockReset().mockResolvedValue(row());vi.mocked(api.approveFinanceMatchException).mockReset().mockResolvedValue(row({matchStatus:'APPROVED_EXCEPTION'}))})
it('shows real source and variances and requires a nonblank bounded reason',async()=>{const w=render();await flushPromises();expect(w.text()).toContain('20%');expect(w.text()).toContain('receipt / real-line');await w.find('textarea').setValue('  ');await click(w,'Approve exception');expect(api.approveFinanceMatchException).not.toHaveBeenCalled();await w.find('textarea').setValue('x'.repeat(501));await click(w,'Approve exception');expect(api.approveFinanceMatchException).not.toHaveBeenCalled();await w.find('textarea').setValue('  verified supplier adjustment  ');await click(w,'Approve exception');expect(api.approveFinanceMatchException).toHaveBeenCalledWith('i','verified supplier adjustment');expect(w.emitted('changed')).toHaveLength(1)})
it('blocks duplicate approval and closing while pending and rereads approval history',async()=>{let resolve!:(v:api.FinanceInvoiceDetail)=>void;vi.mocked(api.approveFinanceMatchException).mockImplementationOnce(()=>new Promise(r=>{resolve=r}));const w=render();await flushPromises();await w.find('textarea').setValue('checked');await click(w,'Approve exception');await click(w,'Approve exception');await click(w,'Close');expect(api.approveFinanceMatchException).toHaveBeenCalledTimes(1);expect(w.emitted('update:modelValue')).toBeUndefined();vi.mocked(api.getFinanceInvoice).mockResolvedValue(row({matchStatus:'APPROVED_EXCEPTION',matchExceptionApprovedBy:'approver',matchExceptionReason:'checked'}));resolve(row());await flushPromises();expect(w.text()).toContain('approver');expect(w.text()).toContain('checked');expect(w.find('textarea').exists()).toBe(false)})
it('refreshes uncertain approval without automatic retry and blocks it if server already approved',async()=>{vi.mocked(api.approveFinanceMatchException).mockRejectedValueOnce(new Error('lost response'));const w=render();await flushPromises();await w.find('textarea').setValue('checked');vi.mocked(api.getFinanceInvoice).mockResolvedValue(row({matchStatus:'APPROVED_EXCEPTION',matchExceptionReason:'checked'}));await click(w,'Approve exception');expect(api.approveFinanceMatchException).toHaveBeenCalledTimes(1);expect(w.text()).toContain('outcome is uncertain');expect(w.findAll('button').some(b=>b.text()==='Approve exception')).toBe(false);expect(w.emitted('changed')).toHaveLength(1)})
it('allows read-only review but makes no requests without view or ALL scope',async()=>{const w=render(['finance:view']);await flushPromises();expect(w.text()).toContain('review only');expect(w.find('textarea').exists()).toBe(false);w.unmount();vi.clearAllMocks();for(const [p,s] of [[['finance:match-exception'],'ALL'],[['finance:view','finance:match-exception'],'SELF']] as const){const denied=render([...p],s);await flushPromises();expect(api.getFinanceInvoice).not.toHaveBeenCalled();denied.unmount()}expect(api.approveFinanceMatchException).not.toHaveBeenCalled()})
it('fails closed on detail read failure and reloads explicitly',async()=>{vi.mocked(api.getFinanceInvoice).mockRejectedValueOnce(new Error('offline'));const w=render();await flushPromises();expect(w.find('textarea').exists()).toBe(false);expect(w.text()).toContain('Unable to read');await click(w,'Reload');expect(w.find('textarea').exists()).toBe(true)})
it('drops stale details and clears reason when changing invoice or reopening',async()=>{let resolve!:(v:api.FinanceInvoiceDetail)=>void;vi.mocked(api.getFinanceInvoice).mockImplementationOnce(()=>new Promise(r=>{resolve=r}));const w=render();await w.setProps({modelValue:false});resolve(row());await flushPromises();expect(w.find('textarea').exists()).toBe(false);await w.setProps({modelValue:true});await flushPromises();await w.find('textarea').setValue('old');vi.mocked(api.getFinanceInvoice).mockResolvedValue(row({id:'new',number:'PI-2'}));await w.setProps({invoiceId:'new'});await flushPromises();expect((w.find('textarea').element as HTMLTextAreaElement).value).toBe('');expect(w.text()).toContain('PI-2')})
it('does not approve posted or non-supplier documents',async()=>{for(const patch of [{status:'POSTED'},{documentType:'SALES_INVOICE'}]){vi.mocked(api.getFinanceInvoice).mockResolvedValue(row(patch));const w=render();await flushPromises();if(w.find('textarea').exists())await w.find('textarea').setValue('reason');await click(w,'Approve exception');expect(api.approveFinanceMatchException).not.toHaveBeenCalled();w.unmount()}})
