/* eslint-disable vue/one-component-per-file -- Focused view stubs. */
import { shallowMount, flushPromises } from '@vue/test-utils'
import { defineComponent } from 'vue'
import { createPinia } from 'pinia'
import { createI18n } from 'vue-i18n'
import { beforeEach, expect, it, vi } from 'vitest'
import { useAuthStore } from '@/stores/auth'
import View from '@/views/FinanceView.vue'
import en from '@/i18n/locales/en-US'
import * as api from '@/api/finance'
import * as native from '@/api/finance-v2'
import * as master from '@/api/master-data'
vi.mock('@/api/finance',()=>({listJournalEntries:vi.fn(),listAccountingPeriods:vi.fn(),getTrialBalance:vi.fn(),getIncomeStatement:vi.fn(),getBalanceSheet:vi.fn(),listPayables:vi.fn(),getReceivableAging:vi.fn(),getPayableAging:vi.fn(),closeAccountingPeriod:vi.fn(),createManualJournal:vi.fn(),createSupplierPayment:vi.fn()}))
vi.mock('@/api/finance-v2',()=>({getFinanceDashboard:vi.fn()}))
vi.mock('@/api/master-data',()=>({getOrganizationSettings:vi.fn()}))
const slot=defineComponent({template:'<div><slot /></div>'})
const button=defineComponent({props:{loading:Boolean},template:'<button :disabled="loading"><slot /></button>'})
const alert=defineComponent({props:{title:{type:String,default:''}},template:'<p role="alert">{{title}}</p>'})
const date=defineComponent({props:{modelValue:{type:String,default:''},placeholder:{type:String,default:''}},emits:['update:modelValue'],template:`<input :placeholder="placeholder" :value="modelValue" @input="$emit('update:modelValue',$event.target.value)" />`})
const closure=defineComponent({emits:['posted'],template:'<button @click="$emit(\'posted\')">Post event</button>'})
const balance=(payables=26.4):native.FinanceDashboard=>({receivables:0,payables,cash:0,revenue:0,expense:0,netIncome:0,trialDebit:0,trialCredit:0,unmatchedBankLines:0,matchExceptions:0})
function render(){const pinia=createPinia();const auth=useAuthStore(pinia);auth.user={id:'u',username:'u',displayName:'u',organizationId:'o',organizationName:'o',departmentId:null,dataScope:'ALL',permissions:['finance:view'],roles:[],mustChangePassword:false};const w=shallowMount(View,{global:{plugins:[pinia,createI18n({legacy:false,locale:'en-US',messages:{'en-US':en}})],stubs:{FinanceClosurePanel:closure,ElCard:slot,ElButton:button,ElAlert:alert,ElDatePicker:date,ElIcon:true,ElTableColumn:true,ElTable:true,ElTag:true,ElEmpty:true,ElTabPane:true,ElTabs:true,ElFormItem:true,ElInput:true,ElInputNumber:true,ElForm:true,ElDialog:true,ElOption:true,ElSelect:true},directives:{loading:()=>{}}}});return {w,auth}}
beforeEach(()=>{vi.resetAllMocks();vi.mocked(api.listJournalEntries).mockResolvedValue({content:[],page:0,size:30,totalElements:0,totalPages:0} as Awaited<ReturnType<typeof api.listJournalEntries>>);vi.mocked(api.listAccountingPeriods).mockResolvedValue({content:[],page:0,size:30,totalElements:0,totalPages:0} as Awaited<ReturnType<typeof api.listAccountingPeriods>>);vi.mocked(api.listPayables).mockResolvedValue({content:[],page:0,size:30,totalElements:0,totalPages:0} as Awaited<ReturnType<typeof api.listPayables>>);vi.mocked(api.getTrialBalance).mockResolvedValue({totalDebit:0} as Awaited<ReturnType<typeof api.getTrialBalance>>);vi.mocked(api.getIncomeStatement).mockResolvedValue({total:0} as Awaited<ReturnType<typeof api.getIncomeStatement>>);vi.mocked(api.getBalanceSheet).mockResolvedValue({total:0} as Awaited<ReturnType<typeof api.getBalanceSheet>>);vi.mocked(api.getReceivableAging).mockResolvedValue([]);vi.mocked(api.getPayableAging).mockResolvedValue([]);vi.mocked(native.getFinanceDashboard).mockResolvedValue(balance());vi.mocked(master.getOrganizationSettings).mockResolvedValue({baseCurrencyCode:'CNY'} as Awaited<ReturnType<typeof master.getOrganizationSettings>>)})
it('shows canonical all-document base balance instead of summing a legacy page or currencies',async()=>{vi.mocked(api.listPayables).mockResolvedValue({content:[{outstandingAmount:999,currencyCode:'USD'}],totalElements:60} as Awaited<ReturnType<typeof api.listPayables>>);const {w}=render();await flushPromises();expect(w.get('[data-testid=payable-balance]').text()).toContain('26.40 CNY');expect(w.get('[data-testid=payable-balance]').text()).not.toContain('999');expect(w.get('[data-testid=payable-balance]').text()).toContain('Independent of the selected date range')})
it('clears unavailable balance and never displays failed reads as zero',async()=>{vi.mocked(native.getFinanceDashboard).mockRejectedValueOnce(new Error('offline'));const {w}=render();await flushPromises();expect(w.get('[data-testid=payable-balance]').text()).toContain('—');expect(w.get('[data-testid=payable-balance]').text()).toContain('Unable to load');expect(w.get('[data-testid=payable-balance]').text()).not.toContain('0.00');await w.findAll('button').find(b=>b.text()==='Refresh')!.trigger('click');await flushPromises();expect(w.get('[data-testid=payable-balance]').text()).toContain('26.40 CNY')})
it('blocks an amount without its base currency and does not use legacy list as fallback',async()=>{vi.mocked(master.getOrganizationSettings).mockRejectedValueOnce(new Error('offline'));const {w}=render();await flushPromises();expect(w.get('[data-testid=payable-balance]').text()).toContain('—');expect(w.get('[data-testid=payable-balance]').text()).toContain('Unable to load')})
it('retains canonical balance if the independent legacy list fails',async()=>{vi.mocked(api.listPayables).mockRejectedValueOnce(new Error('offline'));const {w}=render();await flushPromises();expect(w.get('[data-testid=payable-balance]').text()).toContain('26.40 CNY');expect(w.get('[data-testid=payable-balance]').text()).not.toContain('Unable to load')})
it('refreshes on posting or allocation events using current canonical balance',async()=>{const {w}=render();await flushPromises();vi.mocked(native.getFinanceDashboard).mockResolvedValue(balance(16.4));await w.findAll('button').find(b=>b.text()==='Post event')!.trigger('click');await flushPromises();expect(native.getFinanceDashboard).toHaveBeenCalledTimes(2);expect(w.get('[data-testid=payable-balance]').text()).toContain('16.40 CNY')})
it('uses selected range for the request while the current payable amount remains unchanged',async()=>{const {w}=render();await flushPromises();await w.findAll('input')[0]!.setValue('2026-10-06');await w.findAll('input')[1]!.setValue('2026-10-07');await w.findAll('button').find(b=>b.text()==='Refresh')!.trigger('click');await flushPromises();expect(native.getFinanceDashboard).toHaveBeenLastCalledWith('2026-10-06','2026-10-07');expect(w.get('[data-testid=payable-balance]').text()).toContain('26.40 CNY')})
it('clears previous organization balance and ignores its late response after switching',async()=>{let resolve!:(v:native.FinanceDashboard)=>void;vi.mocked(native.getFinanceDashboard).mockImplementationOnce(()=>new Promise(r=>{resolve=r}));const {w,auth}=render();await flushPromises();expect(w.get('[data-testid=payable-balance]').text()).toContain('—');vi.mocked(native.getFinanceDashboard).mockResolvedValue(balance(7));vi.mocked(master.getOrganizationSettings).mockResolvedValue({baseCurrencyCode:'EUR'} as Awaited<ReturnType<typeof master.getOrganizationSettings>>);auth.user={...auth.user!,organizationId:'new'};await flushPromises();resolve(balance(999));await flushPromises();expect(w.get('[data-testid=payable-balance]').text()).toContain('7.00 EUR');expect(w.get('[data-testid=payable-balance]').text()).not.toContain('999');auth.user=null;await flushPromises();expect(native.getFinanceDashboard).toHaveBeenCalledTimes(2);expect(api.listPayables).toHaveBeenCalledTimes(2);expect(w.get('[data-testid=payable-balance]').text()).toContain('—')})
