/* eslint-disable vue/one-component-per-file -- Focused editor stubs. */
import { mount, flushPromises } from '@vue/test-utils'
import { defineComponent } from 'vue'
import { createPinia } from 'pinia'
import { createI18n } from 'vue-i18n'
import { beforeEach, expect, it, vi } from 'vitest'
import { useAuthStore } from '@/stores/auth'
import Dialog from '@/components/finance/StockInvoiceDialog.vue'
import en from '@/i18n/locales/en-US'
import * as api from '@/api/finance-v2'
vi.mock('@/api/finance-v2', () => ({ listStockInvoiceSources: vi.fn(), createFinanceInvoice: vi.fn() }))
import * as master from '@/api/master-data'
vi.mock('@/api/master-data', () => ({ getOrganizationSettings: vi.fn() }))
const slot = defineComponent({ template: '<div><slot /></div>' })
const button = defineComponent({ props: { disabled: Boolean, loading: Boolean }, template: '<button :disabled="disabled || loading"><slot /></button>' })
const dialog = defineComponent({ props: { modelValue: Boolean }, template: '<section v-if="modelValue"><slot /><slot name="footer" /></section>' })
const select = defineComponent({ props: { modelValue: { type: String, default: '' } }, emits: ['update:modelValue','change'], template: `<select :value="modelValue" @change="$emit('update:modelValue', $event.target.value); $emit('change')"><option value=""></option><slot /></select>` })
const option = defineComponent({ props: { value: { type: String, default: '' }, label: { type: String, default: '' } }, template: '<option :value="value">{{ label }}</option>' })
const alert = defineComponent({ props: { title: { type: String, default: '' } }, template: '<p role="alert">{{ title }}</p>' })
const number = defineComponent({ props: { modelValue: { type: Number, default: 1 } }, emits: ['update:modelValue'], template: `<input type="number" :value="modelValue" @input="$emit('update:modelValue', Number($event.target.value))" />` })
const row = (patch:Partial<api.StockInvoiceSource>={}):api.StockInvoiceSource=>({documentType:'SUPPLIER_INVOICE',sourceType:'PURCHASE_RECEIPT_LINE',sourceId:'receipt',sourceLineId:'rl',sourceNumber:'GR-1',orderNumber:'PO-1',partyId:'supplier',partyName:'Supplier',itemId:'item',description:'Stock',currencyCode:'CNY',quantity:6,remainingQuantity:4,unitPrice:8,discountRate:5,taxRate:10,...patch})
function render(permissions=['finance:view','finance:invoice'],scope:'ALL'|'SELF'='ALL') {const pinia=createPinia();useAuthStore(pinia).user={id:'u',username:'u',displayName:'u',organizationId:'o',organizationName:'o',departmentId:null,dataScope:scope,permissions,roles:[],mustChangePassword:false};return mount(Dialog,{props:{modelValue:true},global:{plugins:[pinia,createI18n({legacy:false,locale:'en-US',messages:{'en-US':en}})],stubs:{ElDialog:dialog,ElButton:button,ElAlert:alert,ElForm:slot,ElFormItem:slot,ElSelect:select,ElOption:option,ElInputNumber:number}}})}
type Wrapper=ReturnType<typeof render>
async function click(w:Wrapper,label:string) {await w.findAll('button').find(b=>b.text()===label)!.trigger('click');await flushPromises()}
async function choose(w:Wrapper,q='2') {await w.find('select').setValue('rl');await w.find('input[type=number]').setValue(q)}
beforeEach(()=>{vi.clearAllMocks();vi.mocked(api.listStockInvoiceSources).mockReset().mockResolvedValue([row()]);vi.mocked(api.createFinanceInvoice).mockReset().mockResolvedValue({} as api.FinanceInvoice);vi.mocked(master.getOrganizationSettings).mockReset().mockResolvedValue({baseCurrencyCode:'CNY'} as Awaited<ReturnType<typeof master.getOrganizationSettings>>)})
it('uses real source identities, party and order terms for partial invoice',async()=>{const w=render();await flushPromises();await choose(w);await click(w,'Save');expect(api.createFinanceInvoice).toHaveBeenCalledWith(expect.objectContaining({documentType:'SUPPLIER_INVOICE',partyId:'supplier',currencyCode:'CNY',exchangeRate:1,lines:[{itemId:'item',description:'Stock',quantity:2,unitPrice:8,discountRate:5,taxRate:10,sources:[{sourceType:'PURCHASE_RECEIPT_LINE',sourceId:'receipt',sourceLineId:'rl',quantity:2,amount:15.2}]}]}),expect.any(String));expect(w.emitted('changed')).toHaveLength(1);expect(w.emitted('update:modelValue')).toEqual([[false]])})
it('filters exhausted, foreign currency and invalid priced sources and blocks quantities outside remainder',async()=>{vi.mocked(api.listStockInvoiceSources).mockResolvedValue([row(),row({sourceLineId:'used',remainingQuantity:0}),row({sourceLineId:'fx',currencyCode:'USD'}),row({sourceLineId:'zero',unitPrice:0})]);const w=render();await flushPromises();expect(w.findAll('option')).toHaveLength(2);await choose(w,'5');await click(w,'Save');await w.find('input').setValue('0');await click(w,'Save');expect(api.createFinanceInvoice).not.toHaveBeenCalled()})
it('supports sales delivery source and defaults to full available quantity',async()=>{vi.mocked(api.listStockInvoiceSources).mockResolvedValue([row({documentType:'SALES_INVOICE',sourceType:'SALES_DELIVERY_LINE',partyId:'customer',remainingQuantity:3})]);const w=render();await flushPromises();await w.find('select').setValue('rl');expect((w.find('input').element as HTMLInputElement).value).toBe('3');await click(w,'Save');expect(api.createFinanceInvoice).toHaveBeenCalledWith(expect.objectContaining({documentType:'SALES_INVOICE',partyId:'customer',lines:[expect.objectContaining({quantity:3,sources:[expect.objectContaining({sourceType:'SALES_DELIVERY_LINE'})]})]}),expect.any(String))})
it('retains stable key for unchanged explicit retry and blocks duplicate pending save and close',async()=>{let reject!:(e:Error)=>void;vi.mocked(api.createFinanceInvoice).mockImplementationOnce(()=>new Promise((_r,j)=>{reject=j}));const w=render();await flushPromises();await choose(w);await click(w,'Save');await click(w,'Save');await click(w,'Close');expect(api.createFinanceInvoice).toHaveBeenCalledTimes(1);expect(w.emitted('update:modelValue')).toBeUndefined();reject(new Error('lost'));await flushPromises();expect(w.text()).toContain('Save outcome is uncertain');await click(w,'Save');expect(vi.mocked(api.createFinanceInvoice).mock.calls[0]![1]).toBe(vi.mocked(api.createFinanceInvoice).mock.calls[1]![1])})
it('creates new key after invoice content changes on failed save',async()=>{vi.mocked(api.createFinanceInvoice).mockRejectedValueOnce(new Error('lost'));const w=render();await flushPromises();await choose(w);await click(w,'Save');await w.find('input').setValue('1');await click(w,'Save');expect(vi.mocked(api.createFinanceInvoice).mock.calls[0]![1]).not.toBe(vi.mocked(api.createFinanceInvoice).mock.calls[1]![1])})
it('fails closed on source or settings loading failure and explicitly reloads',async()=>{vi.mocked(api.listStockInvoiceSources).mockRejectedValueOnce(new Error('offline'));const w=render();await flushPromises();expect(w.find('select').exists()).toBe(false);await click(w,'Save');expect(api.createFinanceInvoice).not.toHaveBeenCalled();await click(w,'Reload');expect(w.find('select').exists()).toBe(true)})
it('requires both permissions and ALL scope and makes no reads without them',async()=>{for(const [p,s] of [[['finance:view'],'ALL'],[['finance:invoice'],'ALL'],[['finance:view','finance:invoice'],'SELF']] as const){const w=render([...p],s);await flushPromises();expect(api.listStockInvoiceSources).not.toHaveBeenCalled();expect(master.getOrganizationSettings).not.toHaveBeenCalled();await click(w,'Save');expect(api.createFinanceInvoice).not.toHaveBeenCalled();w.unmount()}})
it('drops late reads after closing and clears source on reopening',async()=>{let resolve!:(v:api.StockInvoiceSource[])=>void;vi.mocked(api.listStockInvoiceSources).mockImplementationOnce(()=>new Promise(r=>{resolve=r}));const w=render();await w.setProps({modelValue:false});resolve([row()]);await flushPromises();expect(w.find('select').exists()).toBe(false);await w.setProps({modelValue:true});await flushPromises();expect((w.find('select').element as HTMLSelectElement).value).toBe('')})
